BEGIN;

CREATE SCHEMA IF NOT EXISTS world_cup;
SET search_path TO world_cup, public;

CREATE TYPE phase_kind AS ENUM ('GROUP', 'KNOCKOUT', 'PLACEMENT');
CREATE TYPE official_role AS ENUM ('MAIN_REFEREE', 'ASSISTANT_REFEREE_1', 'ASSISTANT_REFEREE_2', 'FOURTH_OFFICIAL');
CREATE TYPE game_event_type AS ENUM (
    'GOAL',
    'OWN_GOAL',
    'PENALTY_GOAL',
    'YELLOW_CARD',
    'RED_CARD',
    'SUBSTITUTION'
);

CREATE TABLE confederation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(10) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL UNIQUE,
    CONSTRAINT confederation_code_uppercase CHECK (code = UPPER(code))
);

CREATE TABLE country (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    fifa_code CHAR(3) NOT NULL UNIQUE,
    confederation_id BIGINT NOT NULL REFERENCES confederation (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT country_fifa_code_uppercase CHECK (fifa_code = UPPER(fifa_code))
);

CREATE TABLE team (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    fifa_code CHAR(3) NOT NULL UNIQUE,
    country_id BIGINT NOT NULL UNIQUE REFERENCES country (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT team_fifa_code_uppercase CHECK (fifa_code = UPPER(fifa_code))
);

CREATE TABLE coach (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(120) NOT NULL,
    birth_date DATE,
    country_id BIGINT REFERENCES country (id) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE referee (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(120) NOT NULL,
    country_id BIGINT REFERENCES country (id) ON UPDATE CASCADE ON DELETE SET NULL,
    UNIQUE (full_name, country_id)
);

CREATE TABLE player (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(120) NOT NULL,
    birth_date DATE NOT NULL,
    primary_position VARCHAR(40) NOT NULL,
    country_of_birth_id BIGINT REFERENCES country (id) ON UPDATE CASCADE ON DELETE SET NULL,
    UNIQUE (full_name, birth_date)
);

CREATE TABLE world_cup_edition (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year SMALLINT NOT NULL UNIQUE,
    host_country_id BIGINT NOT NULL REFERENCES country (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    champion_team_id BIGINT REFERENCES team (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    vice_champion_team_id BIGINT REFERENCES team (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    third_place_team_id BIGINT REFERENCES team (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT edition_year_range CHECK (year BETWEEN 1930 AND 2100),
    CONSTRAINT edition_date_range CHECK (start_date <= end_date),
    CONSTRAINT edition_distinct_top_two CHECK (
        champion_team_id IS NULL
        OR vice_champion_team_id IS NULL
        OR champion_team_id <> vice_champion_team_id
    ),
    CONSTRAINT edition_distinct_third_place CHECK (
        third_place_team_id IS NULL
        OR (
            champion_team_id IS NULL
            OR third_place_team_id <> champion_team_id
        ) AND (
            vice_champion_team_id IS NULL
            OR third_place_team_id <> vice_champion_team_id
        )
    )
);

CREATE TABLE host_city (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    country_id BIGINT NOT NULL REFERENCES country (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    UNIQUE (name, country_id)
);

CREATE TABLE stadium (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    host_city_id BIGINT NOT NULL REFERENCES host_city (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    capacity INTEGER NOT NULL,
    CONSTRAINT stadium_capacity_positive CHECK (capacity > 0),
    UNIQUE (name, host_city_id)
);

CREATE TABLE edition_host_city (
    edition_id BIGINT NOT NULL REFERENCES world_cup_edition (id) ON UPDATE CASCADE ON DELETE CASCADE,
    host_city_id BIGINT NOT NULL REFERENCES host_city (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    PRIMARY KEY (edition_id, host_city_id)
);

CREATE TABLE competition_phase (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(30) NOT NULL UNIQUE,
    display_name VARCHAR(120) NOT NULL UNIQUE,
    phase_kind phase_kind NOT NULL,
    sort_order SMALLINT NOT NULL UNIQUE,
    allows_draw BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT competition_phase_code_uppercase CHECK (code = UPPER(code))
);

CREATE TABLE edition_phase (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    edition_id BIGINT NOT NULL REFERENCES world_cup_edition (id) ON UPDATE CASCADE ON DELETE CASCADE,
    phase_id BIGINT NOT NULL REFERENCES competition_phase (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    label VARCHAR(120) NOT NULL,
    stage_order SMALLINT NOT NULL,
    UNIQUE (edition_id, phase_id),
    UNIQUE (id, edition_id),
    CONSTRAINT edition_phase_order_positive CHECK (stage_order > 0)
);

CREATE TABLE team_group (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    edition_id BIGINT NOT NULL REFERENCES world_cup_edition (id) ON UPDATE CASCADE ON DELETE CASCADE,
    group_letter CHAR(1) NOT NULL,
    UNIQUE (edition_id, group_letter),
    UNIQUE (id, edition_id),
    CONSTRAINT team_group_letter_uppercase CHECK (group_letter = UPPER(group_letter)),
    CONSTRAINT team_group_letter_alpha CHECK (group_letter ~ '^[A-Z]$')
);

CREATE TABLE edition_team (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    edition_id BIGINT NOT NULL REFERENCES world_cup_edition (id) ON UPDATE CASCADE ON DELETE CASCADE,
    team_id BIGINT NOT NULL REFERENCES team (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    coach_id BIGINT NOT NULL REFERENCES coach (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    group_id BIGINT,
    final_rank SMALLINT,
    UNIQUE (edition_id, team_id),
    UNIQUE (edition_id, coach_id),
    UNIQUE (id, edition_id),
    CONSTRAINT edition_team_rank_range CHECK (final_rank IS NULL OR final_rank BETWEEN 1 AND 64),
    CONSTRAINT edition_team_group_fk FOREIGN KEY (group_id, edition_id)
        REFERENCES team_group (id, edition_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);

CREATE TABLE team_call_up (
    edition_id BIGINT NOT NULL,
    team_id BIGINT NOT NULL,
    player_id BIGINT NOT NULL REFERENCES player (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    shirt_number SMALLINT NOT NULL,
    squad_role VARCHAR(30) NOT NULL DEFAULT 'PLAYER',
    primary_position VARCHAR(40) NOT NULL,
    is_captain BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (edition_id, team_id, player_id),
    UNIQUE (edition_id, player_id),
    UNIQUE (edition_id, team_id, shirt_number),
    CONSTRAINT team_call_up_shirt_number_range CHECK (shirt_number BETWEEN 1 AND 99),
    CONSTRAINT team_call_up_role_uppercase CHECK (squad_role = UPPER(squad_role)),
    CONSTRAINT team_call_up_team_fk FOREIGN KEY (edition_id, team_id)
        REFERENCES edition_team (edition_id, team_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE match_game (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    edition_id BIGINT NOT NULL REFERENCES world_cup_edition (id) ON UPDATE CASCADE ON DELETE CASCADE,
    edition_phase_id BIGINT NOT NULL,
    group_id BIGINT,
    stadium_id BIGINT NOT NULL REFERENCES stadium (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    kickoff_at TIMESTAMP NOT NULL,
    home_team_id BIGINT NOT NULL,
    away_team_id BIGINT NOT NULL,
    winner_team_id BIGINT,
    home_score SMALLINT NOT NULL DEFAULT 0,
    away_score SMALLINT NOT NULL DEFAULT 0,
    home_extra_score SMALLINT NOT NULL DEFAULT 0,
    away_extra_score SMALLINT NOT NULL DEFAULT 0,
    home_penalty_score SMALLINT,
    away_penalty_score SMALLINT,
    match_day SMALLINT,
    CONSTRAINT match_phase_fk FOREIGN KEY (edition_phase_id, edition_id)
        REFERENCES edition_phase (id, edition_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT match_group_fk FOREIGN KEY (group_id, edition_id)
        REFERENCES team_group (id, edition_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,
    CONSTRAINT match_home_team_fk FOREIGN KEY (edition_id, home_team_id)
        REFERENCES edition_team (edition_id, team_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT match_away_team_fk FOREIGN KEY (edition_id, away_team_id)
        REFERENCES edition_team (edition_id, team_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT match_winner_team_fk FOREIGN KEY (edition_id, winner_team_id)
        REFERENCES edition_team (edition_id, team_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT match_distinct_teams CHECK (home_team_id <> away_team_id),
    CONSTRAINT match_score_non_negative CHECK (
        home_score >= 0
        AND away_score >= 0
        AND home_extra_score >= 0
        AND away_extra_score >= 0
        AND (home_penalty_score IS NULL OR home_penalty_score >= 0)
        AND (away_penalty_score IS NULL OR away_penalty_score >= 0)
    ),
    CONSTRAINT match_penalties_null_together CHECK (
        (home_penalty_score IS NULL AND away_penalty_score IS NULL)
        OR (home_penalty_score IS NOT NULL AND away_penalty_score IS NOT NULL)
    ),
    CONSTRAINT match_winner_is_participant CHECK (
        winner_team_id IS NULL OR winner_team_id IN (home_team_id, away_team_id)
    )
);

CREATE TABLE match_official (
    match_id BIGINT NOT NULL REFERENCES match_game (id) ON UPDATE CASCADE ON DELETE CASCADE,
    referee_id BIGINT NOT NULL REFERENCES referee (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    role official_role NOT NULL,
    PRIMARY KEY (match_id, referee_id),
    UNIQUE (match_id, role)
);

CREATE TABLE match_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id BIGINT NOT NULL REFERENCES match_game (id) ON UPDATE CASCADE ON DELETE CASCADE,
    event_minute SMALLINT NOT NULL,
    stoppage_minute SMALLINT NOT NULL DEFAULT 0,
    event_type game_event_type NOT NULL,
    team_id BIGINT NOT NULL REFERENCES team (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    player_id BIGINT REFERENCES player (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    related_player_id BIGINT REFERENCES player (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    description TEXT,
    CONSTRAINT match_event_minute_range CHECK (event_minute BETWEEN 0 AND 130),
    CONSTRAINT match_event_stoppage_range CHECK (stoppage_minute BETWEEN 0 AND 30),
    CONSTRAINT match_event_distinct_players CHECK (
        related_player_id IS NULL OR player_id IS NULL OR related_player_id <> player_id
    )
);

CREATE INDEX idx_country_confederation_id ON country (confederation_id);
CREATE INDEX idx_host_city_country_id ON host_city (country_id);
CREATE INDEX idx_stadium_host_city_id ON stadium (host_city_id);
CREATE INDEX idx_edition_team_edition_group ON edition_team (edition_id, group_id);
CREATE INDEX idx_team_call_up_edition_team ON team_call_up (edition_id, team_id);
CREATE INDEX idx_match_game_edition_phase ON match_game (edition_id, edition_phase_id);
CREATE INDEX idx_match_game_group_id ON match_game (group_id);
CREATE INDEX idx_match_event_match_id ON match_event (match_id);
CREATE INDEX idx_match_event_team_id ON match_event (team_id);

CREATE OR REPLACE FUNCTION fn_validate_call_up()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM team_call_up existing_call_up
        WHERE existing_call_up.edition_id = NEW.edition_id
          AND existing_call_up.player_id = NEW.player_id
          AND existing_call_up.team_id <> NEW.team_id
    ) THEN
        RAISE EXCEPTION 'Player % is already assigned to another team in edition %.', NEW.player_id, NEW.edition_id;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM team_call_up existing_call_up
        WHERE existing_call_up.player_id = NEW.player_id
          AND existing_call_up.team_id <> NEW.team_id
    ) THEN
        RAISE EXCEPTION 'Player % cannot switch national teams across editions.', NEW.player_id;
    END IF;

    IF NEW.is_captain AND EXISTS (
        SELECT 1
        FROM team_call_up existing_call_up
        WHERE existing_call_up.edition_id = NEW.edition_id
          AND existing_call_up.team_id = NEW.team_id
          AND existing_call_up.is_captain = TRUE
          AND existing_call_up.player_id <> NEW.player_id
    ) THEN
        RAISE EXCEPTION 'Team % in edition % already has a captain.', NEW.team_id, NEW.edition_id;
    END IF;

    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION fn_validate_edition_podium(p_edition_id BIGINT)
RETURNS VOID
LANGUAGE plpgsql
AS $$
DECLARE
    current_edition world_cup_edition%ROWTYPE;
    rank_one_team_id BIGINT;
    rank_two_team_id BIGINT;
    rank_three_team_id BIGINT;
    rank_one_count BIGINT;
    rank_two_count BIGINT;
    rank_three_count BIGINT;
BEGIN
    SELECT *
    INTO current_edition
    FROM world_cup_edition edition_row
    WHERE edition_row.id = p_edition_id;

    IF NOT FOUND THEN
        RETURN;
    END IF;

    IF current_edition.champion_team_id IS NOT NULL AND NOT EXISTS (
        SELECT 1
        FROM edition_team edition_team_row
        WHERE edition_team_row.edition_id = current_edition.id
          AND edition_team_row.team_id = current_edition.champion_team_id
    ) THEN
        RAISE EXCEPTION 'Champion team % must belong to edition %.', current_edition.champion_team_id, current_edition.id;
    END IF;

    IF current_edition.vice_champion_team_id IS NOT NULL AND NOT EXISTS (
        SELECT 1
        FROM edition_team edition_team_row
        WHERE edition_team_row.edition_id = current_edition.id
          AND edition_team_row.team_id = current_edition.vice_champion_team_id
    ) THEN
        RAISE EXCEPTION 'Vice champion team % must belong to edition %.', current_edition.vice_champion_team_id, current_edition.id;
    END IF;

    IF current_edition.third_place_team_id IS NOT NULL AND NOT EXISTS (
        SELECT 1
        FROM edition_team edition_team_row
        WHERE edition_team_row.edition_id = current_edition.id
          AND edition_team_row.team_id = current_edition.third_place_team_id
    ) THEN
        RAISE EXCEPTION 'Third-place team % must belong to edition %.', current_edition.third_place_team_id, current_edition.id;
    END IF;

    SELECT COUNT(*)::BIGINT
    INTO rank_one_count
    FROM edition_team edition_team_row
    WHERE edition_team_row.edition_id = current_edition.id
      AND edition_team_row.final_rank = 1;

    SELECT COUNT(*)::BIGINT
    INTO rank_two_count
    FROM edition_team edition_team_row
    WHERE edition_team_row.edition_id = current_edition.id
      AND edition_team_row.final_rank = 2;

    SELECT COUNT(*)::BIGINT
    INTO rank_three_count
    FROM edition_team edition_team_row
    WHERE edition_team_row.edition_id = current_edition.id
      AND edition_team_row.final_rank = 3;

    IF rank_one_count > 1 THEN
        RAISE EXCEPTION 'Edition % cannot have more than one team ranked 1.', current_edition.id;
    END IF;

    IF rank_two_count > 1 THEN
        RAISE EXCEPTION 'Edition % cannot have more than one team ranked 2.', current_edition.id;
    END IF;

    IF rank_three_count > 1 THEN
        RAISE EXCEPTION 'Edition % cannot have more than one team ranked 3.', current_edition.id;
    END IF;

    SELECT edition_team_row.team_id
    INTO rank_one_team_id
    FROM edition_team edition_team_row
    WHERE edition_team_row.edition_id = current_edition.id
      AND edition_team_row.final_rank = 1;

    SELECT edition_team_row.team_id
    INTO rank_two_team_id
    FROM edition_team edition_team_row
    WHERE edition_team_row.edition_id = current_edition.id
      AND edition_team_row.final_rank = 2;

    SELECT edition_team_row.team_id
    INTO rank_three_team_id
    FROM edition_team edition_team_row
    WHERE edition_team_row.edition_id = current_edition.id
      AND edition_team_row.final_rank = 3;

    IF current_edition.champion_team_id IS NOT NULL AND rank_one_team_id IS NULL THEN
        RAISE EXCEPTION 'Champion team for edition % requires one edition team ranked 1.', current_edition.id;
    END IF;

    IF current_edition.vice_champion_team_id IS NOT NULL AND rank_two_team_id IS NULL THEN
        RAISE EXCEPTION 'Vice champion team for edition % requires one edition team ranked 2.', current_edition.id;
    END IF;

    IF current_edition.third_place_team_id IS NOT NULL AND rank_three_team_id IS NULL THEN
        RAISE EXCEPTION 'Third-place team for edition % requires one edition team ranked 3.', current_edition.id;
    END IF;

    IF rank_one_team_id IS NOT NULL
       AND current_edition.champion_team_id IS DISTINCT FROM rank_one_team_id THEN
        RAISE EXCEPTION 'Champion team for edition % must match the team ranked 1.', current_edition.id;
    END IF;

    IF rank_two_team_id IS NOT NULL
       AND current_edition.vice_champion_team_id IS DISTINCT FROM rank_two_team_id THEN
        RAISE EXCEPTION 'Vice champion team for edition % must match the team ranked 2.', current_edition.id;
    END IF;

    IF rank_three_team_id IS NOT NULL
       AND current_edition.third_place_team_id IS DISTINCT FROM rank_three_team_id THEN
        RAISE EXCEPTION 'Third-place team for edition % must match the team ranked 3.', current_edition.id;
    END IF;
END;
$$;

CREATE OR REPLACE FUNCTION fn_validate_edition_structure(p_edition_id BIGINT)
RETURNS VOID
LANGUAGE plpgsql
AS $$
DECLARE
    current_host_country_id BIGINT;
BEGIN
    SELECT edition_row.host_country_id
    INTO current_host_country_id
    FROM world_cup_edition edition_row
    WHERE edition_row.id = p_edition_id;

    IF current_host_country_id IS NULL THEN
        RETURN;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM edition_host_city edition_host_city_row
        WHERE edition_host_city_row.edition_id = p_edition_id
    ) THEN
        RAISE EXCEPTION 'Edition % must have at least one host city.', p_edition_id;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM edition_phase edition_phase_row
        WHERE edition_phase_row.edition_id = p_edition_id
    ) THEN
        RAISE EXCEPTION 'Edition % must have at least one phase.', p_edition_id;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM edition_host_city edition_host_city_row
        JOIN host_city host_city_row ON host_city_row.id = edition_host_city_row.host_city_id
        WHERE edition_host_city_row.edition_id = p_edition_id
          AND host_city_row.country_id <> current_host_country_id
    ) THEN
        RAISE EXCEPTION 'Every host city for edition % must belong to the edition host country.', p_edition_id;
    END IF;
END;
$$;

CREATE OR REPLACE FUNCTION fn_enforce_edition_structure()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    target_edition_id BIGINT;
BEGIN
    IF TG_TABLE_NAME = 'world_cup_edition' THEN
        IF TG_OP = 'DELETE' THEN
            target_edition_id := OLD.id;
        ELSE
            target_edition_id := NEW.id;
        END IF;
    ELSE
        IF TG_OP = 'DELETE' THEN
            target_edition_id := OLD.edition_id;
        ELSE
            target_edition_id := NEW.edition_id;
        END IF;
    END IF;

    PERFORM fn_validate_edition_structure(target_edition_id);

    RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION fn_enforce_edition_podium()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    target_edition_id BIGINT;
BEGIN
    IF TG_TABLE_NAME = 'world_cup_edition' THEN
        IF TG_OP = 'DELETE' THEN
            target_edition_id := OLD.id;
        ELSE
            target_edition_id := NEW.id;
        END IF;
    ELSE
        IF TG_OP = 'DELETE' THEN
            target_edition_id := OLD.edition_id;
        ELSE
            target_edition_id := NEW.edition_id;
        END IF;
    END IF;

    PERFORM fn_validate_edition_podium(target_edition_id);

    RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION fn_validate_match_game()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    current_phase_kind phase_kind;
    current_allows_draw BOOLEAN;
    home_total_goals INTEGER;
    away_total_goals INTEGER;
BEGIN
    SELECT phase.phase_kind, phase.allows_draw
    INTO current_phase_kind, current_allows_draw
    FROM edition_phase edition_phase_row
    JOIN competition_phase phase ON phase.id = edition_phase_row.phase_id
    WHERE edition_phase_row.id = NEW.edition_phase_id
      AND edition_phase_row.edition_id = NEW.edition_id;

    IF current_phase_kind IS NULL THEN
        RAISE EXCEPTION 'Edition phase % does not belong to edition %.', NEW.edition_phase_id, NEW.edition_id;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM edition_host_city edition_host_city_row
        JOIN stadium stadium_row ON stadium_row.host_city_id = edition_host_city_row.host_city_id
        WHERE edition_host_city_row.edition_id = NEW.edition_id
          AND stadium_row.id = NEW.stadium_id
    ) THEN
        RAISE EXCEPTION 'Stadium % is not registered as a host venue for edition %.', NEW.stadium_id, NEW.edition_id;
    END IF;

    home_total_goals := NEW.home_score + NEW.home_extra_score;
    away_total_goals := NEW.away_score + NEW.away_extra_score;

    IF current_phase_kind = 'GROUP' THEN
        IF NEW.group_id IS NULL THEN
            RAISE EXCEPTION 'Group-stage matches must belong to a group.';
        END IF;

        IF EXISTS (
            SELECT 1
            FROM edition_team edition_team_row
            WHERE edition_team_row.edition_id = NEW.edition_id
              AND edition_team_row.team_id IN (NEW.home_team_id, NEW.away_team_id)
              AND edition_team_row.group_id IS DISTINCT FROM NEW.group_id
        ) THEN
            RAISE EXCEPTION 'Both teams must belong to the same group for a group-stage match.';
        END IF;

        IF NEW.home_penalty_score IS NOT NULL OR NEW.away_penalty_score IS NOT NULL THEN
            RAISE EXCEPTION 'Group-stage matches cannot have penalty shootouts.';
        END IF;

        IF NEW.winner_team_id IS NOT NULL THEN
            IF home_total_goals = away_total_goals THEN
                RAISE EXCEPTION 'Drawn group-stage matches cannot declare a winner.';
            END IF;

            IF (
                home_total_goals > away_total_goals AND NEW.winner_team_id <> NEW.home_team_id
            ) OR (
                away_total_goals > home_total_goals AND NEW.winner_team_id <> NEW.away_team_id
            ) THEN
                RAISE EXCEPTION 'Winner team does not match the scoreline for group-stage match %.', NEW.id;
            END IF;
        END IF;
    ELSE
        IF NEW.group_id IS NOT NULL THEN
            RAISE EXCEPTION 'Knockout and placement matches cannot reference a group.';
        END IF;

        IF NEW.winner_team_id IS NULL THEN
            RAISE EXCEPTION 'Non-group matches must declare a qualified team.';
        END IF;

        IF current_allows_draw THEN
            RAISE EXCEPTION 'Knockout-style phases cannot allow draws.';
        END IF;

        IF home_total_goals = away_total_goals THEN
            IF NEW.home_penalty_score IS NULL OR NEW.away_penalty_score IS NULL THEN
                RAISE EXCEPTION 'Tied knockout matches require penalty scores.';
            END IF;

            IF NEW.home_penalty_score = NEW.away_penalty_score THEN
                RAISE EXCEPTION 'Penalty shootouts cannot finish tied.';
            END IF;

            IF (
                NEW.home_penalty_score > NEW.away_penalty_score AND NEW.winner_team_id <> NEW.home_team_id
            ) OR (
                NEW.away_penalty_score > NEW.home_penalty_score AND NEW.winner_team_id <> NEW.away_team_id
            ) THEN
                RAISE EXCEPTION 'Winner team does not match the penalty shootout outcome.';
            END IF;
        ELSE
            IF NEW.home_penalty_score IS NOT NULL OR NEW.away_penalty_score IS NOT NULL THEN
                RAISE EXCEPTION 'Penalty scores are only allowed when the knockout match is tied after extra time.';
            END IF;

            IF (
                home_total_goals > away_total_goals AND NEW.winner_team_id <> NEW.home_team_id
            ) OR (
                away_total_goals > home_total_goals AND NEW.winner_team_id <> NEW.away_team_id
            ) THEN
                RAISE EXCEPTION 'Winner team does not match the final score.';
            END IF;
        END IF;
    END IF;

    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION fn_validate_match_event()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    current_edition_id BIGINT;
    current_home_team_id BIGINT;
    current_away_team_id BIGINT;
BEGIN
    SELECT match_row.edition_id, match_row.home_team_id, match_row.away_team_id
    INTO current_edition_id, current_home_team_id, current_away_team_id
    FROM match_game match_row
    WHERE match_row.id = NEW.match_id;

    IF current_edition_id IS NULL THEN
        RAISE EXCEPTION 'Match % does not exist.', NEW.match_id;
    END IF;

    IF NEW.team_id NOT IN (current_home_team_id, current_away_team_id) THEN
        RAISE EXCEPTION 'Event team % is not part of match %.', NEW.team_id, NEW.match_id;
    END IF;

    IF NEW.event_type = 'SUBSTITUTION' THEN
        IF NEW.player_id IS NULL OR NEW.related_player_id IS NULL THEN
            RAISE EXCEPTION 'Substitution events must declare outgoing and incoming players.';
        END IF;
    ELSE
        IF NEW.player_id IS NULL THEN
            RAISE EXCEPTION 'Event type % requires a player.', NEW.event_type;
        END IF;

        IF NEW.related_player_id IS NOT NULL THEN
            RAISE EXCEPTION 'Event type % cannot declare a secondary player.', NEW.event_type;
        END IF;
    END IF;

    IF NEW.player_id IS NOT NULL AND NOT EXISTS (
        SELECT 1
        FROM team_call_up call_up
        WHERE call_up.edition_id = current_edition_id
          AND call_up.team_id = NEW.team_id
          AND call_up.player_id = NEW.player_id
    ) THEN
        RAISE EXCEPTION 'Player % is not registered for team % in edition %.', NEW.player_id, NEW.team_id, current_edition_id;
    END IF;

    IF NEW.related_player_id IS NOT NULL AND NOT EXISTS (
        SELECT 1
        FROM team_call_up call_up
        WHERE call_up.edition_id = current_edition_id
          AND call_up.team_id = NEW.team_id
          AND call_up.player_id = NEW.related_player_id
    ) THEN
        RAISE EXCEPTION 'Related player % is not registered for team % in edition %.', NEW.related_player_id, NEW.team_id, current_edition_id;
    END IF;

    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION fn_validate_generated_sql(p_sql TEXT)
RETURNS TEXT
LANGUAGE plpgsql
AS $$
DECLARE
    normalized_sql TEXT;
BEGIN
    normalized_sql := btrim(p_sql);

    IF normalized_sql IS NULL OR normalized_sql = '' THEN
        RAISE EXCEPTION 'Generated SQL cannot be empty.';
    END IF;

    normalized_sql := regexp_replace(normalized_sql, ';+\s*$', '');
    normalized_sql := btrim(normalized_sql);

    IF normalized_sql = '' THEN
        RAISE EXCEPTION 'Generated SQL cannot be empty after normalization.';
    END IF;

    IF normalized_sql ~ ';' THEN
        RAISE EXCEPTION 'Generated SQL must contain exactly one statement.';
    END IF;

    IF normalized_sql ~ '(^|[^:])--' OR normalized_sql ~ '/\*' THEN
        RAISE EXCEPTION 'Generated SQL cannot contain SQL comments.';
    END IF;

    IF normalized_sql !~* '^(SELECT|WITH)\M' THEN
        RAISE EXCEPTION 'Generated SQL must start with SELECT or WITH.';
    END IF;

    IF normalized_sql ~* '\m(INSERT|UPDATE|DELETE|MERGE|DROP|ALTER|CREATE|TRUNCATE|GRANT|REVOKE|COPY|CALL|DO|EXECUTE|PREPARE|DEALLOCATE|VACUUM|ANALYZE|REFRESH|SET|RESET|SHOW|BEGIN|COMMIT|ROLLBACK|SAVEPOINT|LOCK|DISCARD|LISTEN|NOTIFY|UNLISTEN)\M' THEN
        RAISE EXCEPTION 'Generated SQL contains a forbidden command.';
    END IF;

    IF normalized_sql ~* '\m(pg_catalog|information_schema|pg_toast|pg_temp)\.' THEN
        RAISE EXCEPTION 'Generated SQL cannot access PostgreSQL system schemas.';
    END IF;

    RETURN normalized_sql;
END;
$$;

CREATE TRIGGER trg_validate_call_up
BEFORE INSERT OR UPDATE ON team_call_up
FOR EACH ROW
EXECUTE FUNCTION fn_validate_call_up();

CREATE TRIGGER trg_validate_match_game
BEFORE INSERT OR UPDATE ON match_game
FOR EACH ROW
EXECUTE FUNCTION fn_validate_match_game();

CREATE TRIGGER trg_validate_match_event
BEFORE INSERT OR UPDATE ON match_event
FOR EACH ROW
EXECUTE FUNCTION fn_validate_match_event();

CREATE CONSTRAINT TRIGGER trg_enforce_edition_structure_on_edition
AFTER INSERT OR UPDATE ON world_cup_edition
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION fn_enforce_edition_structure();

CREATE CONSTRAINT TRIGGER trg_enforce_edition_structure_on_host_city
AFTER INSERT OR UPDATE OR DELETE ON edition_host_city
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION fn_enforce_edition_structure();

CREATE CONSTRAINT TRIGGER trg_enforce_edition_structure_on_phase
AFTER INSERT OR UPDATE OR DELETE ON edition_phase
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION fn_enforce_edition_structure();

CREATE CONSTRAINT TRIGGER trg_enforce_edition_podium_on_edition
AFTER INSERT OR UPDATE ON world_cup_edition
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION fn_enforce_edition_podium();

CREATE CONSTRAINT TRIGGER trg_enforce_edition_podium_on_team
AFTER INSERT OR UPDATE OR DELETE ON edition_team
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION fn_enforce_edition_podium();


COMMIT;
