BEGIN;

CREATE SCHEMA IF NOT EXISTS world_cup;
SET search_path TO world_cup, public;

CREATE TYPE phase_kind AS ENUM ('GROUP', 'KNOCKOUT', 'PLACEMENT');
CREATE TYPE official_role AS ENUM ('MAIN_REFEREE', 'ASSISTANT_REFEREE_1', 'ASSISTANT_REFEREE_2', 'FOURTH_OFFICIAL');
CREATE TYPE game_event_type AS ENUM (
    'GOAL',
    'OWN_GOAL',
    'PENALTY_GOAL',
    'YELLOW_CARD',
    'RED_CARD',
    'SUBSTITUTION'
);

CREATE TABLE confederation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(10) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL UNIQUE,
    CONSTRAINT confederation_code_uppercase CHECK (code = UPPER(code))
);

CREATE TABLE country (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    fifa_code CHAR(3) NOT NULL UNIQUE,
    confederation_id BIGINT NOT NULL REFERENCES confederation (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT country_fifa_code_uppercase CHECK (fifa_code = UPPER(fifa_code))
);

CREATE TABLE team (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    fifa_code CHAR(3) NOT NULL UNIQUE,
    country_id BIGINT NOT NULL UNIQUE REFERENCES country (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT team_fifa_code_uppercase CHECK (fifa_code = UPPER(fifa_code))
);

CREATE TABLE coach (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(120) NOT NULL,
    birth_date DATE,
    country_id BIGINT REFERENCES country (id) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE referee (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(120) NOT NULL,
    country_id BIGINT REFERENCES country (id) ON UPDATE CASCADE ON DELETE SET NULL,
    UNIQUE (full_name, country_id)
);

CREATE TABLE player (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(120) NOT NULL,
    birth_date DATE NOT NULL,
    primary_position VARCHAR(40) NOT NULL,
    country_of_birth_id BIGINT REFERENCES country (id) ON UPDATE CASCADE ON DELETE SET NULL,
    UNIQUE (full_name, birth_date)
);

CREATE TABLE world_cup_edition (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year SMALLINT NOT NULL UNIQUE,
    host_country_id BIGINT NOT NULL REFERENCES country (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    champion_team_id BIGINT REFERENCES team (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    vice_champion_team_id BIGINT REFERENCES team (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    third_place_team_id BIGINT REFERENCES team (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT edition_year_range CHECK (year BETWEEN 1930 AND 2100),
    CONSTRAINT edition_date_range CHECK (start_date <= end_date),
    CONSTRAINT edition_distinct_top_two CHECK (
        champion_team_id IS NULL
        OR vice_champion_team_id IS NULL
        OR champion_team_id <> vice_champion_team_id
    ),
    CONSTRAINT edition_distinct_third_place CHECK (
        third_place_team_id IS NULL
        OR (
            champion_team_id IS NULL
            OR third_place_team_id <> champion_team_id
        ) AND (
            vice_champion_team_id IS NULL
            OR third_place_team_id <> vice_champion_team_id
        )
    )
);

CREATE TABLE host_city (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    country_id BIGINT NOT NULL REFERENCES country (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    UNIQUE (name, country_id)
);

CREATE TABLE stadium (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    host_city_id BIGINT NOT NULL REFERENCES host_city (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    capacity INTEGER NOT NULL,
    CONSTRAINT stadium_capacity_positive CHECK (capacity > 0),
    UNIQUE (name, host_city_id)
);

CREATE TABLE edition_host_city (
    edition_id BIGINT NOT NULL REFERENCES world_cup_edition (id) ON UPDATE CASCADE ON DELETE CASCADE,
    host_city_id BIGINT NOT NULL REFERENCES host_city (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    PRIMARY KEY (edition_id, host_city_id)
);

CREATE TABLE competition_phase (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(30) NOT NULL UNIQUE,
    display_name VARCHAR(120) NOT NULL UNIQUE,
    phase_kind phase_kind NOT NULL,
    sort_order SMALLINT NOT NULL UNIQUE,
    allows_draw BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT competition_phase_code_uppercase CHECK (code = UPPER(code))
);

CREATE TABLE edition_phase (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    edition_id BIGINT NOT NULL REFERENCES world_cup_edition (id) ON UPDATE CASCADE ON DELETE CASCADE,
    phase_id BIGINT NOT NULL REFERENCES competition_phase (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    label VARCHAR(120) NOT NULL,
    stage_order SMALLINT NOT NULL,
    UNIQUE (edition_id, phase_id),
    UNIQUE (id, edition_id),
    CONSTRAINT edition_phase_order_positive CHECK (stage_order > 0)
);

CREATE TABLE team_group (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    edition_id BIGINT NOT NULL REFERENCES world_cup_edition (id) ON UPDATE CASCADE ON DELETE CASCADE,
    group_letter CHAR(1) NOT NULL,
    UNIQUE (edition_id, group_letter),
    UNIQUE (id, edition_id),
    CONSTRAINT team_group_letter_uppercase CHECK (group_letter = UPPER(group_letter)),
    CONSTRAINT team_group_letter_alpha CHECK (group_letter ~ '^[A-Z]$')
);

CREATE TABLE edition_team (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    edition_id BIGINT NOT NULL REFERENCES world_cup_edition (id) ON UPDATE CASCADE ON DELETE CASCADE,
    team_id BIGINT NOT NULL REFERENCES team (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    coach_id BIGINT NOT NULL REFERENCES coach (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    group_id BIGINT,
    final_rank SMALLINT,
    UNIQUE (edition_id, team_id),
    UNIQUE (edition_id, coach_id),
    UNIQUE (id, edition_id),
    CONSTRAINT edition_team_rank_range CHECK (final_rank IS NULL OR final_rank BETWEEN 1 AND 64),
    CONSTRAINT edition_team_group_fk FOREIGN KEY (group_id, edition_id)
        REFERENCES team_group (id, edition_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);

CREATE TABLE team_call_up (
    edition_id BIGINT NOT NULL,
    team_id BIGINT NOT NULL,
    player_id BIGINT NOT NULL REFERENCES player (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    shirt_number SMALLINT NOT NULL,
    squad_role VARCHAR(30) NOT NULL DEFAULT 'PLAYER',
    primary_position VARCHAR(40) NOT NULL,
    is_captain BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (edition_id, team_id, player_id),
    UNIQUE (edition_id, player_id),
    UNIQUE (edition_id, team_id, shirt_number),
    CONSTRAINT team_call_up_shirt_number_range CHECK (shirt_number BETWEEN 1 AND 99),
    CONSTRAINT team_call_up_role_uppercase CHECK (squad_role = UPPER(squad_role)),
    CONSTRAINT team_call_up_team_fk FOREIGN KEY (edition_id, team_id)
        REFERENCES edition_team (edition_id, team_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

CREATE TABLE match_game (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    edition_id BIGINT NOT NULL REFERENCES world_cup_edition (id) ON UPDATE CASCADE ON DELETE CASCADE,
    edition_phase_id BIGINT NOT NULL,
    group_id BIGINT,
    stadium_id BIGINT NOT NULL REFERENCES stadium (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    kickoff_at TIMESTAMP NOT NULL,
    home_team_id BIGINT NOT NULL,
    away_team_id BIGINT NOT NULL,
    winner_team_id BIGINT,
    home_score SMALLINT NOT NULL DEFAULT 0,
    away_score SMALLINT NOT NULL DEFAULT 0,
    home_extra_score SMALLINT NOT NULL DEFAULT 0,
    away_extra_score SMALLINT NOT NULL DEFAULT 0,
    home_penalty_score SMALLINT,
    away_penalty_score SMALLINT,
    match_day SMALLINT,
    CONSTRAINT match_phase_fk FOREIGN KEY (edition_phase_id, edition_id)
        REFERENCES edition_phase (id, edition_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT match_group_fk FOREIGN KEY (group_id, edition_id)
        REFERENCES team_group (id, edition_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,
    CONSTRAINT match_home_team_fk FOREIGN KEY (edition_id, home_team_id)
        REFERENCES edition_team (edition_id, team_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT match_away_team_fk FOREIGN KEY (edition_id, away_team_id)
        REFERENCES edition_team (edition_id, team_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT match_winner_team_fk FOREIGN KEY (edition_id, winner_team_id)
        REFERENCES edition_team (edition_id, team_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT match_distinct_teams CHECK (home_team_id <> away_team_id),
    CONSTRAINT match_score_non_negative CHECK (
        home_score >= 0
        AND away_score >= 0
        AND home_extra_score >= 0
        AND away_extra_score >= 0
        AND (home_penalty_score IS NULL OR home_penalty_score >= 0)
        AND (away_penalty_score IS NULL OR away_penalty_score >= 0)
    ),
    CONSTRAINT match_penalties_null_together CHECK (
        (home_penalty_score IS NULL AND away_penalty_score IS NULL)
        OR (home_penalty_score IS NOT NULL AND away_penalty_score IS NOT NULL)
    ),
    CONSTRAINT match_winner_is_participant CHECK (
        winner_team_id IS NULL OR winner_team_id IN (home_team_id, away_team_id)
    )
);

CREATE TABLE match_official (
    match_id BIGINT NOT NULL REFERENCES match_game (id) ON UPDATE CASCADE ON DELETE CASCADE,
    referee_id BIGINT NOT NULL REFERENCES referee (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    role official_role NOT NULL,
    PRIMARY KEY (match_id, referee_id),
    UNIQUE (match_id, role)
);

CREATE TABLE match_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id BIGINT NOT NULL REFERENCES match_game (id) ON UPDATE CASCADE ON DELETE CASCADE,
    event_minute SMALLINT NOT NULL,
    stoppage_minute SMALLINT NOT NULL DEFAULT 0,
    event_type game_event_type NOT NULL,
    team_id BIGINT NOT NULL REFERENCES team (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    player_id BIGINT REFERENCES player (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    related_player_id BIGINT REFERENCES player (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    description TEXT,
    CONSTRAINT match_event_minute_range CHECK (event_minute BETWEEN 0 AND 130),
    CONSTRAINT match_event_stoppage_range CHECK (stoppage_minute BETWEEN 0 AND 30),
    CONSTRAINT match_event_distinct_players CHECK (
        related_player_id IS NULL OR player_id IS NULL OR related_player_id <> player_id
    )
);

CREATE INDEX idx_country_confederation_id ON country (confederation_id);
CREATE INDEX idx_host_city_country_id ON host_city (country_id);
CREATE INDEX idx_stadium_host_city_id ON stadium (host_city_id);
CREATE INDEX idx_edition_team_edition_group ON edition_team (edition_id, group_id);
CREATE INDEX idx_team_call_up_edition_team ON team_call_up (edition_id, team_id);
CREATE INDEX idx_match_game_edition_phase ON match_game (edition_id, edition_phase_id);
CREATE INDEX idx_match_game_group_id ON match_game (group_id);
CREATE INDEX idx_match_event_match_id ON match_event (match_id);
CREATE INDEX idx_match_event_team_id ON match_event (team_id);

CREATE OR REPLACE FUNCTION fn_validate_call_up()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM team_call_up existing_call_up
        WHERE existing_call_up.edition_id = NEW.edition_id
          AND existing_call_up.player_id = NEW.player_id
          AND existing_call_up.team_id <> NEW.team_id
    ) THEN
        RAISE EXCEPTION 'Player % is already assigned to another team in edition %.', NEW.player_id, NEW.edition_id;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM team_call_up existing_call_up
        WHERE existing_call_up.player_id = NEW.player_id
          AND existing_call_up.team_id <> NEW.team_id
    ) THEN
        RAISE EXCEPTION 'Player % cannot switch national teams across editions.', NEW.player_id;
    END IF;

    IF NEW.is_captain AND EXISTS (
        SELECT 1
        FROM team_call_up existing_call_up
        WHERE existing_call_up.edition_id = NEW.edition_id
          AND existing_call_up.team_id = NEW.team_id
          AND existing_call_up.is_captain = TRUE
          AND existing_call_up.player_id <> NEW.player_id
    ) THEN
        RAISE EXCEPTION 'Team % in edition % already has a captain.', NEW.team_id, NEW.edition_id;
    END IF;

    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION fn_validate_edition_podium(p_edition_id BIGINT)
RETURNS VOID
LANGUAGE plpgsql
AS $$
DECLARE
    current_edition world_cup_edition%ROWTYPE;
    rank_one_team_id BIGINT;
    rank_two_team_id BIGINT;
    rank_three_team_id BIGINT;
    rank_one_count BIGINT;
    rank_two_count BIGINT;
    rank_three_count BIGINT;
BEGIN
    SELECT *
    INTO current_edition
    FROM world_cup_edition edition_row
    WHERE edition_row.id = p_edition_id;

    IF NOT FOUND THEN
        RETURN;
    END IF;

    IF current_edition.champion_team_id IS NOT NULL AND NOT EXISTS (
        SELECT 1
        FROM edition_team edition_team_row
        WHERE edition_team_row.edition_id = current_edition.id
          AND edition_team_row.team_id = current_edition.champion_team_id
    ) THEN
        RAISE EXCEPTION 'Champion team % must belong to edition %.', current_edition.champion_team_id, current_edition.id;
    END IF;

    IF current_edition.vice_champion_team_id IS NOT NULL AND NOT EXISTS (
        SELECT 1
        FROM edition_team edition_team_row
        WHERE edition_team_row.edition_id = current_edition.id
          AND edition_team_row.team_id = current_edition.vice_champion_team_id
    ) THEN
        RAISE EXCEPTION 'Vice champion team % must belong to edition %.', current_edition.vice_champion_team_id, current_edition.id;
    END IF;

    IF current_edition.third_place_team_id IS NOT NULL AND NOT EXISTS (
        SELECT 1
        FROM edition_team edition_team_row
        WHERE edition_team_row.edition_id = current_edition.id
          AND edition_team_row.team_id = current_edition.third_place_team_id
    ) THEN
        RAISE EXCEPTION 'Third-place team % must belong to edition %.', current_edition.third_place_team_id, current_edition.id;
    END IF;

    SELECT COUNT(*)::BIGINT
    INTO rank_one_count
    FROM edition_team edition_team_row
    WHERE edition_team_row.edition_id = current_edition.id
      AND edition_team_row.final_rank = 1;

    SELECT COUNT(*)::BIGINT
    INTO rank_two_count
    FROM edition_team edition_team_row
    WHERE edition_team_row.edition_id = current_edition.id
      AND edition_team_row.final_rank = 2;

    SELECT COUNT(*)::BIGINT
    INTO rank_three_count
    FROM edition_team edition_team_row
    WHERE edition_team_row.edition_id = current_edition.id
      AND edition_team_row.final_rank = 3;

    IF rank_one_count > 1 THEN
        RAISE EXCEPTION 'Edition % cannot have more than one team ranked 1.', current_edition.id;
    END IF;

    IF rank_two_count > 1 THEN
        RAISE EXCEPTION 'Edition % cannot have more than one team ranked 2.', current_edition.id;
    END IF;

    IF rank_three_count > 1 THEN
        RAISE EXCEPTION 'Edition % cannot have more than one team ranked 3.', current_edition.id;
    END IF;

    SELECT edition_team_row.team_id
    INTO rank_one_team_id
    FROM edition_team edition_team_row
    WHERE edition_team_row.edition_id = current_edition.id
      AND edition_team_row.final_rank = 1;

    SELECT edition_team_row.team_id
    INTO rank_two_team_id
    FROM edition_team edition_team_row
    WHERE edition_team_row.edition_id = current_edition.id
      AND edition_team_row.final_rank = 2;

    SELECT edition_team_row.team_id
    INTO rank_three_team_id
    FROM edition_team edition_team_row
    WHERE edition_team_row.edition_id = current_edition.id
      AND edition_team_row.final_rank = 3;

    IF current_edition.champion_team_id IS NOT NULL AND rank_one_team_id IS NULL THEN
        RAISE EXCEPTION 'Champion team for edition % requires one edition team ranked 1.', current_edition.id;
    END IF;

    IF current_edition.vice_champion_team_id IS NOT NULL AND rank_two_team_id IS NULL THEN
        RAISE EXCEPTION 'Vice champion team for edition % requires one edition team ranked 2.', current_edition.id;
    END IF;

    IF current_edition.third_place_team_id IS NOT NULL AND rank_three_team_id IS NULL THEN
        RAISE EXCEPTION 'Third-place team for edition % requires one edition team ranked 3.', current_edition.id;
    END IF;

    IF rank_one_team_id IS NOT NULL
       AND current_edition.champion_team_id IS DISTINCT FROM rank_one_team_id THEN
        RAISE EXCEPTION 'Champion team for edition % must match the team ranked 1.', current_edition.id;
    END IF;

    IF rank_two_team_id IS NOT NULL
       AND current_edition.vice_champion_team_id IS DISTINCT FROM rank_two_team_id THEN
        RAISE EXCEPTION 'Vice champion team for edition % must match the team ranked 2.', current_edition.id;
    END IF;

    IF rank_three_team_id IS NOT NULL
       AND current_edition.third_place_team_id IS DISTINCT FROM rank_three_team_id THEN
        RAISE EXCEPTION 'Third-place team for edition % must match the team ranked 3.', current_edition.id;
    END IF;
END;
$$;

CREATE OR REPLACE FUNCTION fn_validate_edition_structure(p_edition_id BIGINT)
RETURNS VOID
LANGUAGE plpgsql
AS $$
DECLARE
    current_host_country_id BIGINT;
BEGIN
    SELECT edition_row.host_country_id
    INTO current_host_country_id
    FROM world_cup_edition edition_row
    WHERE edition_row.id = p_edition_id;

    IF current_host_country_id IS NULL THEN
        RETURN;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM edition_host_city edition_host_city_row
        WHERE edition_host_city_row.edition_id = p_edition_id
    ) THEN
        RAISE EXCEPTION 'Edition % must have at least one host city.', p_edition_id;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM edition_phase edition_phase_row
        WHERE edition_phase_row.edition_id = p_edition_id
    ) THEN
        RAISE EXCEPTION 'Edition % must have at least one phase.', p_edition_id;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM edition_host_city edition_host_city_row
        JOIN host_city host_city_row ON host_city_row.id = edition_host_city_row.host_city_id
        WHERE edition_host_city_row.edition_id = p_edition_id
          AND host_city_row.country_id <> current_host_country_id
    ) THEN
        RAISE EXCEPTION 'Every host city for edition % must belong to the edition host country.', p_edition_id;
    END IF;
END;
$$;

CREATE OR REPLACE FUNCTION fn_enforce_edition_structure()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    target_edition_id BIGINT;
BEGIN
    IF TG_TABLE_NAME = 'world_cup_edition' THEN
        IF TG_OP = 'DELETE' THEN
            target_edition_id := OLD.id;
        ELSE
            target_edition_id := NEW.id;
        END IF;
    ELSE
        IF TG_OP = 'DELETE' THEN
            target_edition_id := OLD.edition_id;
        ELSE
            target_edition_id := NEW.edition_id;
        END IF;
    END IF;

    PERFORM fn_validate_edition_structure(target_edition_id);

    RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION fn_enforce_edition_podium()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    target_edition_id BIGINT;
BEGIN
    IF TG_TABLE_NAME = 'world_cup_edition' THEN
        IF TG_OP = 'DELETE' THEN
            target_edition_id := OLD.id;
        ELSE
            target_edition_id := NEW.id;
        END IF;
    ELSE
        IF TG_OP = 'DELETE' THEN
            target_edition_id := OLD.edition_id;
        ELSE
            target_edition_id := NEW.edition_id;
        END IF;
    END IF;

    PERFORM fn_validate_edition_podium(target_edition_id);

    RETURN NULL;
END;
$$;

CREATE OR REPLACE FUNCTION fn_validate_match_game()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    current_phase_kind phase_kind;
    current_allows_draw BOOLEAN;
    home_total_goals INTEGER;
    away_total_goals INTEGER;
BEGIN
    SELECT phase.phase_kind, phase.allows_draw
    INTO current_phase_kind, current_allows_draw
    FROM edition_phase edition_phase_row
    JOIN competition_phase phase ON phase.id = edition_phase_row.phase_id
    WHERE edition_phase_row.id = NEW.edition_phase_id
      AND edition_phase_row.edition_id = NEW.edition_id;

    IF current_phase_kind IS NULL THEN
        RAISE EXCEPTION 'Edition phase % does not belong to edition %.', NEW.edition_phase_id, NEW.edition_id;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM edition_host_city edition_host_city_row
        JOIN stadium stadium_row ON stadium_row.host_city_id = edition_host_city_row.host_city_id
        WHERE edition_host_city_row.edition_id = NEW.edition_id
          AND stadium_row.id = NEW.stadium_id
    ) THEN
        RAISE EXCEPTION 'Stadium % is not registered as a host venue for edition %.', NEW.stadium_id, NEW.edition_id;
    END IF;

    home_total_goals := NEW.home_score + NEW.home_extra_score;
    away_total_goals := NEW.away_score + NEW.away_extra_score;

    IF current_phase_kind = 'GROUP' THEN
        IF NEW.group_id IS NULL THEN
            RAISE EXCEPTION 'Group-stage matches must belong to a group.';
        END IF;

        IF EXISTS (
            SELECT 1
            FROM edition_team edition_team_row
            WHERE edition_team_row.edition_id = NEW.edition_id
              AND edition_team_row.team_id IN (NEW.home_team_id, NEW.away_team_id)
              AND edition_team_row.group_id IS DISTINCT FROM NEW.group_id
        ) THEN
            RAISE EXCEPTION 'Both teams must belong to the same group for a group-stage match.';
        END IF;

        IF NEW.home_penalty_score IS NOT NULL OR NEW.away_penalty_score IS NOT NULL THEN
            RAISE EXCEPTION 'Group-stage matches cannot have penalty shootouts.';
        END IF;

        IF NEW.winner_team_id IS NOT NULL THEN
            IF home_total_goals = away_total_goals THEN
                RAISE EXCEPTION 'Drawn group-stage matches cannot declare a winner.';
            END IF;

            IF (
                home_total_goals > away_total_goals AND NEW.winner_team_id <> NEW.home_team_id
            ) OR (
                away_total_goals > home_total_goals AND NEW.winner_team_id <> NEW.away_team_id
            ) THEN
                RAISE EXCEPTION 'Winner team does not match the scoreline for group-stage match %.', NEW.id;
            END IF;
        END IF;
    ELSE
        IF NEW.group_id IS NOT NULL THEN
            RAISE EXCEPTION 'Knockout and placement matches cannot reference a group.';
        END IF;

        IF NEW.winner_team_id IS NULL THEN
            RAISE EXCEPTION 'Non-group matches must declare a qualified team.';
        END IF;

        IF current_allows_draw THEN
            RAISE EXCEPTION 'Knockout-style phases cannot allow draws.';
        END IF;

        IF home_total_goals = away_total_goals THEN
            IF NEW.home_penalty_score IS NULL OR NEW.away_penalty_score IS NULL THEN
                RAISE EXCEPTION 'Tied knockout matches require penalty scores.';
            END IF;

            IF NEW.home_penalty_score = NEW.away_penalty_score THEN
                RAISE EXCEPTION 'Penalty shootouts cannot finish tied.';
            END IF;

            IF (
                NEW.home_penalty_score > NEW.away_penalty_score AND NEW.winner_team_id <> NEW.home_team_id
            ) OR (
                NEW.away_penalty_score > NEW.home_penalty_score AND NEW.winner_team_id <> NEW.away_team_id
            ) THEN
                RAISE EXCEPTION 'Winner team does not match the penalty shootout outcome.';
            END IF;
        ELSE
            IF NEW.home_penalty_score IS NOT NULL OR NEW.away_penalty_score IS NOT NULL THEN
                RAISE EXCEPTION 'Penalty scores are only allowed when the knockout match is tied after extra time.';
            END IF;

            IF (
                home_total_goals > away_total_goals AND NEW.winner_team_id <> NEW.home_team_id
            ) OR (
                away_total_goals > home_total_goals AND NEW.winner_team_id <> NEW.away_team_id
            ) THEN
                RAISE EXCEPTION 'Winner team does not match the final score.';
            END IF;
        END IF;
    END IF;

    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION fn_validate_match_event()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    current_edition_id BIGINT;
    current_home_team_id BIGINT;
    current_away_team_id BIGINT;
BEGIN
    SELECT match_row.edition_id, match_row.home_team_id, match_row.away_team_id
    INTO current_edition_id, current_home_team_id, current_away_team_id
    FROM match_game match_row
    WHERE match_row.id = NEW.match_id;

    IF current_edition_id IS NULL THEN
        RAISE EXCEPTION 'Match % does not exist.', NEW.match_id;
    END IF;

    IF NEW.team_id NOT IN (current_home_team_id, current_away_team_id) THEN
        RAISE EXCEPTION 'Event team % is not part of match %.', NEW.team_id, NEW.match_id;
    END IF;

    IF NEW.event_type = 'SUBSTITUTION' THEN
        IF NEW.player_id IS NULL OR NEW.related_player_id IS NULL THEN
            RAISE EXCEPTION 'Substitution events must declare outgoing and incoming players.';
        END IF;
    ELSE
        IF NEW.player_id IS NULL THEN
            RAISE EXCEPTION 'Event type % requires a player.', NEW.event_type;
        END IF;

        IF NEW.related_player_id IS NOT NULL THEN
            RAISE EXCEPTION 'Event type % cannot declare a secondary player.', NEW.event_type;
        END IF;
    END IF;

    IF NEW.player_id IS NOT NULL AND NOT EXISTS (
        SELECT 1
        FROM team_call_up call_up
        WHERE call_up.edition_id = current_edition_id
          AND call_up.team_id = NEW.team_id
          AND call_up.player_id = NEW.player_id
    ) THEN
        RAISE EXCEPTION 'Player % is not registered for team % in edition %.', NEW.player_id, NEW.team_id, current_edition_id;
    END IF;

    IF NEW.related_player_id IS NOT NULL AND NOT EXISTS (
        SELECT 1
        FROM team_call_up call_up
        WHERE call_up.edition_id = current_edition_id
          AND call_up.team_id = NEW.team_id
          AND call_up.player_id = NEW.related_player_id
    ) THEN
        RAISE EXCEPTION 'Related player % is not registered for team % in edition %.', NEW.related_player_id, NEW.team_id, current_edition_id;
    END IF;

    RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION fn_validate_generated_sql(p_sql TEXT)
RETURNS TEXT
LANGUAGE plpgsql
AS $$
DECLARE
    normalized_sql TEXT;
BEGIN
    normalized_sql := btrim(p_sql);

    IF normalized_sql IS NULL OR normalized_sql = '' THEN
        RAISE EXCEPTION 'Generated SQL cannot be empty.';
    END IF;

    normalized_sql := regexp_replace(normalized_sql, ';+\s*$', '');
    normalized_sql := btrim(normalized_sql);

    IF normalized_sql = '' THEN
        RAISE EXCEPTION 'Generated SQL cannot be empty after normalization.';
    END IF;

    IF normalized_sql ~ ';' THEN
        RAISE EXCEPTION 'Generated SQL must contain exactly one statement.';
    END IF;

    IF normalized_sql ~ '(^|[^:])--' OR normalized_sql ~ '/\*' THEN
        RAISE EXCEPTION 'Generated SQL cannot contain SQL comments.';
    END IF;

    IF normalized_sql !~* '^(SELECT|WITH)\M' THEN
        RAISE EXCEPTION 'Generated SQL must start with SELECT or WITH.';
    END IF;

    IF normalized_sql ~* '\m(INSERT|UPDATE|DELETE|MERGE|DROP|ALTER|CREATE|TRUNCATE|GRANT|REVOKE|COPY|CALL|DO|EXECUTE|PREPARE|DEALLOCATE|VACUUM|ANALYZE|REFRESH|SET|RESET|SHOW|BEGIN|COMMIT|ROLLBACK|SAVEPOINT|LOCK|DISCARD|LISTEN|NOTIFY|UNLISTEN)\M' THEN
        RAISE EXCEPTION 'Generated SQL contains a forbidden command.';
    END IF;

    IF normalized_sql ~* '\m(pg_catalog|information_schema|pg_toast|pg_temp)\.' THEN
        RAISE EXCEPTION 'Generated SQL cannot access PostgreSQL system schemas.';
    END IF;

    RETURN normalized_sql;
END;
$$;

CREATE TRIGGER trg_validate_call_up
BEFORE INSERT OR UPDATE ON team_call_up
FOR EACH ROW
EXECUTE FUNCTION fn_validate_call_up();

CREATE TRIGGER trg_validate_match_game
BEFORE INSERT OR UPDATE ON match_game
FOR EACH ROW
EXECUTE FUNCTION fn_validate_match_game();

CREATE TRIGGER trg_validate_match_event
BEFORE INSERT OR UPDATE ON match_event
FOR EACH ROW
EXECUTE FUNCTION fn_validate_match_event();

CREATE CONSTRAINT TRIGGER trg_enforce_edition_structure_on_edition
AFTER INSERT OR UPDATE ON world_cup_edition
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION fn_enforce_edition_structure();

CREATE CONSTRAINT TRIGGER trg_enforce_edition_structure_on_host_city
AFTER INSERT OR UPDATE OR DELETE ON edition_host_city
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION fn_enforce_edition_structure();

CREATE CONSTRAINT TRIGGER trg_enforce_edition_structure_on_phase
AFTER INSERT OR UPDATE OR DELETE ON edition_phase
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION fn_enforce_edition_structure();

CREATE CONSTRAINT TRIGGER trg_enforce_edition_podium_on_edition
AFTER INSERT OR UPDATE ON world_cup_edition
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION fn_enforce_edition_podium();

CREATE CONSTRAINT TRIGGER trg_enforce_edition_podium_on_team
AFTER INSERT OR UPDATE OR DELETE ON edition_team
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW
EXECUTE FUNCTION fn_enforce_edition_podium();

CREATE OR REPLACE VIEW vw_match_scoreboard AS
SELECT
    match_row.id AS match_id,
    match_row.edition_id,
    edition_row.year AS edition_year,
    edition_phase_row.stage_order,
    phase_row.code AS phase_code,
    phase_row.display_name AS phase_name,
    phase_row.phase_kind,
    team_group_row.group_letter,
    match_row.match_day,
    match_row.kickoff_at,
    stadium_row.name AS stadium_name,
    host_city_row.name AS host_city_name,
    match_row.home_team_id,
    home_team.name AS home_team_name,
    match_row.away_team_id,
    away_team.name AS away_team_name,
    match_row.winner_team_id,
    winner_team.name AS winner_team_name,
    match_row.home_score,
    match_row.away_score,
    match_row.home_extra_score,
    match_row.away_extra_score,
    match_row.home_penalty_score,
    match_row.away_penalty_score,
    match_row.home_score + match_row.home_extra_score AS final_home_goals,
    match_row.away_score + match_row.away_extra_score AS final_away_goals
FROM match_game match_row
JOIN world_cup_edition edition_row ON edition_row.id = match_row.edition_id
JOIN edition_phase edition_phase_row ON edition_phase_row.id = match_row.edition_phase_id
JOIN competition_phase phase_row ON phase_row.id = edition_phase_row.phase_id
JOIN stadium stadium_row ON stadium_row.id = match_row.stadium_id
JOIN host_city host_city_row ON host_city_row.id = stadium_row.host_city_id
JOIN team home_team ON home_team.id = match_row.home_team_id
JOIN team away_team ON away_team.id = match_row.away_team_id
LEFT JOIN team winner_team ON winner_team.id = match_row.winner_team_id
LEFT JOIN team_group team_group_row ON team_group_row.id = match_row.group_id;

CREATE OR REPLACE VIEW vw_match_team_summary AS
SELECT
    scoreboard.match_id,
    scoreboard.edition_id,
    scoreboard.edition_year,
    scoreboard.phase_code,
    scoreboard.phase_name,
    scoreboard.phase_kind,
    scoreboard.group_letter,
    scoreboard.kickoff_at,
    scoreboard.home_team_id AS team_id,
    scoreboard.home_team_name AS team_name,
    scoreboard.away_team_id AS opponent_team_id,
    scoreboard.away_team_name AS opponent_team_name,
    scoreboard.final_home_goals AS goals_for,
    scoreboard.final_away_goals AS goals_against,
    CASE
        WHEN scoreboard.phase_kind = 'GROUP' AND scoreboard.final_home_goals > scoreboard.final_away_goals THEN 'WIN'
        WHEN scoreboard.phase_kind = 'GROUP' AND scoreboard.final_home_goals < scoreboard.final_away_goals THEN 'LOSS'
        WHEN scoreboard.phase_kind = 'GROUP' THEN 'DRAW'
        WHEN scoreboard.winner_team_id = scoreboard.home_team_id THEN 'WIN'
        ELSE 'LOSS'
    END AS result,
    CASE
        WHEN scoreboard.phase_kind <> 'GROUP' THEN NULL
        WHEN scoreboard.final_home_goals > scoreboard.final_away_goals THEN 3
        WHEN scoreboard.final_home_goals = scoreboard.final_away_goals THEN 1
        ELSE 0
    END AS points
FROM vw_match_scoreboard scoreboard
UNION ALL
SELECT
    scoreboard.match_id,
    scoreboard.edition_id,
    scoreboard.edition_year,
    scoreboard.phase_code,
    scoreboard.phase_name,
    scoreboard.phase_kind,
    scoreboard.group_letter,
    scoreboard.kickoff_at,
    scoreboard.away_team_id AS team_id,
    scoreboard.away_team_name AS team_name,
    scoreboard.home_team_id AS opponent_team_id,
    scoreboard.home_team_name AS opponent_team_name,
    scoreboard.final_away_goals AS goals_for,
    scoreboard.final_home_goals AS goals_against,
    CASE
        WHEN scoreboard.phase_kind = 'GROUP' AND scoreboard.final_away_goals > scoreboard.final_home_goals THEN 'WIN'
        WHEN scoreboard.phase_kind = 'GROUP' AND scoreboard.final_away_goals < scoreboard.final_home_goals THEN 'LOSS'
        WHEN scoreboard.phase_kind = 'GROUP' THEN 'DRAW'
        WHEN scoreboard.winner_team_id = scoreboard.away_team_id THEN 'WIN'
        ELSE 'LOSS'
    END AS result,
    CASE
        WHEN scoreboard.phase_kind <> 'GROUP' THEN NULL
        WHEN scoreboard.final_away_goals > scoreboard.final_home_goals THEN 3
        WHEN scoreboard.final_away_goals = scoreboard.final_home_goals THEN 1
        ELSE 0
    END AS points
FROM vw_match_scoreboard scoreboard;

CREATE OR REPLACE FUNCTION fn_list_editions()
RETURNS TABLE (
    edition_id BIGINT,
    edition_year SMALLINT,
    host_country VARCHAR(100),
    champion_team VARCHAR(100),
    vice_champion_team VARCHAR(100),
    third_place_team VARCHAR(100)
)
LANGUAGE sql
AS $$
    SELECT
        edition_row.id AS edition_id,
        edition_row.year AS edition_year,
        host_country.name AS host_country,
        champion_team.name AS champion_team,
        vice_team.name AS vice_champion_team,
        third_team.name AS third_place_team
    FROM world_cup_edition edition_row
    JOIN country host_country ON host_country.id = edition_row.host_country_id
    LEFT JOIN team champion_team ON champion_team.id = edition_row.champion_team_id
    LEFT JOIN team vice_team ON vice_team.id = edition_row.vice_champion_team_id
    LEFT JOIN team third_team ON third_team.id = edition_row.third_place_team_id
    ORDER BY edition_row.year;
$$;

CREATE OR REPLACE FUNCTION fn_list_edition_teams(p_edition_id BIGINT)
RETURNS TABLE (
    edition_id BIGINT,
    edition_year SMALLINT,
    team_id BIGINT,
    team_name VARCHAR(100),
    country_name VARCHAR(100),
    coach_name VARCHAR(120),
    group_letter CHAR(1),
    final_rank SMALLINT
)
LANGUAGE sql
AS $$
    SELECT
        edition_team_row.edition_id,
        edition_row.year AS edition_year,
        team_row.id AS team_id,
        team_row.name AS team_name,
        country_row.name AS country_name,
        coach_row.full_name AS coach_name,
        team_group_row.group_letter,
        edition_team_row.final_rank
    FROM edition_team edition_team_row
    JOIN world_cup_edition edition_row ON edition_row.id = edition_team_row.edition_id
    JOIN team team_row ON team_row.id = edition_team_row.team_id
    JOIN country country_row ON country_row.id = team_row.country_id
    JOIN coach coach_row ON coach_row.id = edition_team_row.coach_id
    LEFT JOIN team_group team_group_row ON team_group_row.id = edition_team_row.group_id
    WHERE edition_team_row.edition_id = p_edition_id
    ORDER BY team_group_row.group_letter NULLS LAST, team_row.name;
$$;

CREATE OR REPLACE FUNCTION fn_list_all_edition_teams()
RETURNS TABLE (
    edition_id BIGINT,
    edition_year SMALLINT,
    team_id BIGINT,
    team_name VARCHAR(100),
    country_name VARCHAR(100),
    coach_name VARCHAR(120),
    group_letter CHAR(1),
    final_rank SMALLINT
)
LANGUAGE sql
AS $$
    SELECT
        edition_team_row.edition_id,
        edition_row.year AS edition_year,
        team_row.id AS team_id,
        team_row.name AS team_name,
        country_row.name AS country_name,
        coach_row.full_name AS coach_name,
        team_group_row.group_letter,
        edition_team_row.final_rank
    FROM edition_team edition_team_row
    JOIN world_cup_edition edition_row ON edition_row.id = edition_team_row.edition_id
    JOIN team team_row ON team_row.id = edition_team_row.team_id
    JOIN country country_row ON country_row.id = team_row.country_id
    JOIN coach coach_row ON coach_row.id = edition_team_row.coach_id
    LEFT JOIN team_group team_group_row ON team_group_row.id = edition_team_row.group_id
    ORDER BY edition_row.year DESC, team_group_row.group_letter NULLS LAST, team_row.name;
$$;

CREATE OR REPLACE FUNCTION fn_list_edition_groups(p_edition_id BIGINT)
RETURNS TABLE (
    edition_id BIGINT,
    edition_year SMALLINT,
    group_id BIGINT,
    group_letter CHAR(1),
    team_id BIGINT,
    team_name VARCHAR(100),
    coach_name VARCHAR(120)
)
LANGUAGE sql
AS $$
    SELECT
        team_group_row.edition_id,
        edition_row.year AS edition_year,
        team_group_row.id AS group_id,
        team_group_row.group_letter,
        team_row.id AS team_id,
        team_row.name AS team_name,
        coach_row.full_name AS coach_name
    FROM team_group team_group_row
    JOIN world_cup_edition edition_row ON edition_row.id = team_group_row.edition_id
    LEFT JOIN edition_team edition_team_row
        ON edition_team_row.group_id = team_group_row.id
       AND edition_team_row.edition_id = team_group_row.edition_id
    LEFT JOIN team team_row ON team_row.id = edition_team_row.team_id
    LEFT JOIN coach coach_row ON coach_row.id = edition_team_row.coach_id
    WHERE team_group_row.edition_id = p_edition_id
    ORDER BY team_group_row.group_letter, team_row.name;
$$;

CREATE OR REPLACE FUNCTION fn_group_standings(p_group_id BIGINT)
RETURNS TABLE (
    rank_position BIGINT,
    group_id BIGINT,
    group_letter CHAR(1),
    team_id BIGINT,
    team_name VARCHAR(100),
    matches_played BIGINT,
    wins BIGINT,
    draws BIGINT,
    losses BIGINT,
    goals_for BIGINT,
    goals_against BIGINT,
    goal_difference BIGINT,
    points BIGINT
)
LANGUAGE sql
AS $$
    WITH standings_base AS (
        SELECT
            team_group_row.id AS group_id,
            team_group_row.group_letter,
            edition_team_row.team_id,
            team_row.name AS team_name,
            COUNT(summary_row.match_id) AS matches_played,
            COUNT(*) FILTER (WHERE summary_row.result = 'WIN') AS wins,
            COUNT(*) FILTER (WHERE summary_row.result = 'DRAW') AS draws,
            COUNT(*) FILTER (WHERE summary_row.result = 'LOSS') AS losses,
            COALESCE(SUM(summary_row.goals_for), 0) AS goals_for,
            COALESCE(SUM(summary_row.goals_against), 0) AS goals_against,
            COALESCE(SUM(summary_row.points), 0) AS points
        FROM team_group team_group_row
        JOIN edition_team edition_team_row
            ON edition_team_row.group_id = team_group_row.id
           AND edition_team_row.edition_id = team_group_row.edition_id
        JOIN team team_row ON team_row.id = edition_team_row.team_id
        LEFT JOIN vw_match_team_summary summary_row
            ON summary_row.edition_id = team_group_row.edition_id
           AND summary_row.team_id = edition_team_row.team_id
           AND summary_row.phase_kind = 'GROUP'
           AND summary_row.group_letter = team_group_row.group_letter
        WHERE team_group_row.id = p_group_id
        GROUP BY team_group_row.id, team_group_row.group_letter, edition_team_row.team_id, team_row.name
    )
    SELECT
        ROW_NUMBER() OVER (
            ORDER BY standings_base.points DESC,
                     (standings_base.goals_for - standings_base.goals_against) DESC,
                     standings_base.goals_for DESC,
                     standings_base.team_name
        ) AS rank_position,
        standings_base.group_id,
        standings_base.group_letter,
        standings_base.team_id,
        standings_base.team_name,
        standings_base.matches_played,
        standings_base.wins,
        standings_base.draws,
        standings_base.losses,
        standings_base.goals_for,
        standings_base.goals_against,
        standings_base.goals_for - standings_base.goals_against AS goal_difference,
        standings_base.points
    FROM standings_base
    ORDER BY rank_position;
$$;

CREATE OR REPLACE FUNCTION fn_list_edition_matches(p_edition_id BIGINT)
RETURNS TABLE (
    match_id BIGINT,
    edition_id BIGINT,
    edition_year SMALLINT,
    phase_name VARCHAR(120),
    group_letter CHAR(1),
    kickoff_at TIMESTAMP,
    stadium_name VARCHAR(120),
    host_city_name VARCHAR(120),
    home_team_name VARCHAR(100),
    away_team_name VARCHAR(100),
    final_score VARCHAR(20),
    penalty_score VARCHAR(20),
    winner_team_name VARCHAR(100)
)
LANGUAGE sql
AS $$
    SELECT
        scoreboard.match_id,
        scoreboard.edition_id,
        scoreboard.edition_year,
        scoreboard.phase_name,
        scoreboard.group_letter,
        scoreboard.kickoff_at,
        scoreboard.stadium_name,
        scoreboard.host_city_name,
        scoreboard.home_team_name,
        scoreboard.away_team_name,
        scoreboard.final_home_goals::VARCHAR || ' - ' || scoreboard.final_away_goals::VARCHAR AS final_score,
        CASE
            WHEN scoreboard.home_penalty_score IS NULL THEN NULL
            ELSE scoreboard.home_penalty_score::VARCHAR || ' - ' || scoreboard.away_penalty_score::VARCHAR
        END AS penalty_score,
        scoreboard.winner_team_name
    FROM vw_match_scoreboard scoreboard
    WHERE scoreboard.edition_id = p_edition_id
    ORDER BY scoreboard.kickoff_at, scoreboard.match_id;
$$;

CREATE OR REPLACE FUNCTION fn_knockout_path(p_edition_id BIGINT)
RETURNS TABLE (
    match_id BIGINT,
    edition_year SMALLINT,
    phase_name VARCHAR(120),
    kickoff_at TIMESTAMP,
    stadium_name VARCHAR(120),
    home_team_name VARCHAR(100),
    away_team_name VARCHAR(100),
    final_score VARCHAR(20),
    penalty_score VARCHAR(20),
    winner_team_name VARCHAR(100)
)
LANGUAGE sql
AS $$
    SELECT
        scoreboard.match_id,
        scoreboard.edition_year,
        scoreboard.phase_name,
        scoreboard.kickoff_at,
        scoreboard.stadium_name,
        scoreboard.home_team_name,
        scoreboard.away_team_name,
        scoreboard.final_home_goals::VARCHAR || ' - ' || scoreboard.final_away_goals::VARCHAR AS final_score,
        CASE
            WHEN scoreboard.home_penalty_score IS NULL THEN NULL
            ELSE scoreboard.home_penalty_score::VARCHAR || ' - ' || scoreboard.away_penalty_score::VARCHAR
        END AS penalty_score,
        scoreboard.winner_team_name
    FROM vw_match_scoreboard scoreboard
    WHERE scoreboard.edition_id = p_edition_id
      AND scoreboard.phase_kind <> 'GROUP'
    ORDER BY scoreboard.stage_order, scoreboard.kickoff_at, scoreboard.match_id;
$$;

CREATE OR REPLACE FUNCTION fn_list_team_squad(p_edition_id BIGINT, p_team_id BIGINT)
RETURNS TABLE (
    edition_id BIGINT,
    edition_year SMALLINT,
    team_id BIGINT,
    team_name VARCHAR(100),
    shirt_number SMALLINT,
    player_id BIGINT,
    player_name VARCHAR(120),
    primary_position VARCHAR(40),
    squad_role VARCHAR(30),
    is_captain BOOLEAN
)
LANGUAGE sql
AS $$
    SELECT
        call_up.edition_id,
        edition_row.year AS edition_year,
        call_up.team_id,
        team_row.name AS team_name,
        call_up.shirt_number,
        player_row.id AS player_id,
        player_row.full_name AS player_name,
        call_up.primary_position,
        call_up.squad_role,
        call_up.is_captain
    FROM team_call_up call_up
    JOIN world_cup_edition edition_row ON edition_row.id = call_up.edition_id
    JOIN team team_row ON team_row.id = call_up.team_id
    JOIN player player_row ON player_row.id = call_up.player_id
    WHERE call_up.edition_id = p_edition_id
      AND call_up.team_id = p_team_id
    ORDER BY call_up.shirt_number, player_row.full_name;
$$;

CREATE OR REPLACE FUNCTION fn_list_match_events(p_match_id BIGINT)
RETURNS TABLE (
    event_id BIGINT,
    match_id BIGINT,
    minute_label VARCHAR(10),
    event_type game_event_type,
    team_name VARCHAR(100),
    player_name VARCHAR(120),
    related_player_name VARCHAR(120),
    description TEXT
)
LANGUAGE sql
AS $$
    SELECT
        event_row.id AS event_id,
        event_row.match_id,
        CASE
            WHEN event_row.stoppage_minute = 0 THEN event_row.event_minute::VARCHAR
            ELSE event_row.event_minute::VARCHAR || '+' || event_row.stoppage_minute::VARCHAR
        END AS minute_label,
        event_row.event_type,
        team_row.name AS team_name,
        player_row.full_name AS player_name,
        related_player_row.full_name AS related_player_name,
        event_row.description
    FROM match_event event_row
    JOIN team team_row ON team_row.id = event_row.team_id
    LEFT JOIN player player_row ON player_row.id = event_row.player_id
    LEFT JOIN player related_player_row ON related_player_row.id = event_row.related_player_id
    WHERE event_row.match_id = p_match_id
    ORDER BY event_row.event_minute, event_row.stoppage_minute, event_row.id;
$$;

CREATE OR REPLACE FUNCTION fn_top_scorers(p_edition_id BIGINT)
RETURNS TABLE (
    rank_position BIGINT,
    edition_id BIGINT,
    edition_year SMALLINT,
    player_id BIGINT,
    player_name VARCHAR(120),
    team_id BIGINT,
    team_name VARCHAR(100),
    total_goals BIGINT
)
LANGUAGE sql
AS $$
    WITH scorer_base AS (
        SELECT
            match_row.edition_id,
            edition_row.year AS edition_year,
            event_row.player_id,
            player_row.full_name AS player_name,
            call_up.team_id,
            team_row.name AS team_name,
            COUNT(*) AS total_goals
        FROM match_event event_row
        JOIN match_game match_row ON match_row.id = event_row.match_id
        JOIN world_cup_edition edition_row ON edition_row.id = match_row.edition_id
        JOIN player player_row ON player_row.id = event_row.player_id
        JOIN team_call_up call_up
            ON call_up.edition_id = match_row.edition_id
           AND call_up.player_id = event_row.player_id
        JOIN team team_row ON team_row.id = call_up.team_id
        WHERE match_row.edition_id = p_edition_id
          AND event_row.event_type IN ('GOAL', 'PENALTY_GOAL')
        GROUP BY
            match_row.edition_id,
            edition_row.year,
            event_row.player_id,
            player_row.full_name,
            call_up.team_id,
            team_row.name
    )
    SELECT
        ROW_NUMBER() OVER (ORDER BY scorer_base.total_goals DESC, scorer_base.player_name) AS rank_position,
        scorer_base.edition_id,
        scorer_base.edition_year,
        scorer_base.player_id,
        scorer_base.player_name,
        scorer_base.team_id,
        scorer_base.team_name,
        scorer_base.total_goals
    FROM scorer_base
    ORDER BY rank_position;
$$;

CREATE OR REPLACE FUNCTION fn_team_history(p_team_id BIGINT)
RETURNS TABLE (
    edition_id BIGINT,
    edition_year SMALLINT,
    team_id BIGINT,
    team_name VARCHAR(100),
    final_rank SMALLINT,
    matches_played BIGINT,
    wins BIGINT,
    draws BIGINT,
    losses BIGINT,
    goals_for BIGINT,
    goals_against BIGINT
)
LANGUAGE sql
AS $$
    SELECT
        edition_team_row.edition_id,
        edition_row.year AS edition_year,
        edition_team_row.team_id,
        team_row.name AS team_name,
        edition_team_row.final_rank,
        COUNT(summary_row.match_id) AS matches_played,
        COUNT(*) FILTER (WHERE summary_row.result = 'WIN') AS wins,
        COUNT(*) FILTER (WHERE summary_row.result = 'DRAW') AS draws,
        COUNT(*) FILTER (WHERE summary_row.result = 'LOSS') AS losses,
        COALESCE(SUM(summary_row.goals_for), 0) AS goals_for,
        COALESCE(SUM(summary_row.goals_against), 0) AS goals_against
    FROM edition_team edition_team_row
    JOIN world_cup_edition edition_row ON edition_row.id = edition_team_row.edition_id
    JOIN team team_row ON team_row.id = edition_team_row.team_id
    LEFT JOIN vw_match_team_summary summary_row
        ON summary_row.edition_id = edition_team_row.edition_id
       AND summary_row.team_id = edition_team_row.team_id
    WHERE edition_team_row.team_id = p_team_id
    GROUP BY
        edition_team_row.edition_id,
        edition_row.year,
        edition_team_row.team_id,
        team_row.name,
        edition_team_row.final_rank
    ORDER BY edition_row.year;
$$;

COMMIT;
