BEGIN;

SET search_path TO world_cup, public;

CREATE TABLE synthetic_seed_batch (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dataset_key VARCHAR(80) NOT NULL,
    edition_years SMALLINT[] NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    cleaned_at TIMESTAMPTZ,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT synthetic_seed_batch_timeline CHECK (
        cleaned_at IS NULL OR cleaned_at >= created_at
    )
);

CREATE TABLE synthetic_seed_registry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL REFERENCES synthetic_seed_batch (id) ON UPDATE CASCADE ON DELETE CASCADE,
    table_name VARCHAR(63) NOT NULL,
    primary_key JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT synthetic_seed_registry_pk_object CHECK (jsonb_typeof(primary_key) = 'object'),
    UNIQUE (batch_id, table_name, primary_key)
);

CREATE UNIQUE INDEX idx_synthetic_seed_batch_single_active
    ON synthetic_seed_batch (is_active)
    WHERE is_active = TRUE;

CREATE INDEX idx_synthetic_seed_registry_batch_table
    ON synthetic_seed_registry (batch_id, table_name);

CREATE OR REPLACE FUNCTION fn_internal_acquire_synthetic_seed_lock()
RETURNS VOID
LANGUAGE plpgsql
SET search_path = world_cup, public
AS $$
BEGIN
    PERFORM pg_advisory_xact_lock(hashtextextended('world_cup.synthetic_seed', 0));
END;
$$;

CREATE OR REPLACE FUNCTION fn_internal_register_synthetic_row(
    p_batch_id BIGINT,
    p_table_name TEXT,
    p_primary_key JSONB
)
RETURNS VOID
LANGUAGE plpgsql
SET search_path = world_cup, public
AS $$
BEGIN
    INSERT INTO synthetic_seed_registry (batch_id, table_name, primary_key)
    VALUES (p_batch_id, p_table_name, p_primary_key);
END;
$$;

CREATE OR REPLACE FUNCTION fn_internal_synthetic_batch_summary(p_batch_id BIGINT)
RETURNS TABLE (
    batch_id BIGINT,
    dataset_key VARCHAR(80),
    edition_years SMALLINT[],
    created_at TIMESTAMPTZ,
    cleaned_at TIMESTAMPTZ,
    table_counts JSONB,
    total_rows BIGINT
)
LANGUAGE sql
SET search_path = world_cup, public
AS $$
    WITH registry_counts AS (
        SELECT
            registry_row.batch_id,
            registry_row.table_name,
            COUNT(*)::BIGINT AS row_count
        FROM synthetic_seed_registry registry_row
        WHERE registry_row.batch_id = p_batch_id
        GROUP BY registry_row.batch_id, registry_row.table_name
    )
    SELECT
        batch_row.id AS batch_id,
        batch_row.dataset_key,
        batch_row.edition_years,
        batch_row.created_at,
        batch_row.cleaned_at,
        COALESCE(
            jsonb_object_agg(registry_counts.table_name, registry_counts.row_count ORDER BY registry_counts.table_name)
                FILTER (WHERE registry_counts.table_name IS NOT NULL),
            '{}'::JSONB
        ) AS table_counts,
        COALESCE(SUM(registry_counts.row_count), 0)::BIGINT AS total_rows
    FROM synthetic_seed_batch batch_row
    LEFT JOIN registry_counts ON registry_counts.batch_id = batch_row.id
    WHERE batch_row.id = p_batch_id
    GROUP BY
        batch_row.id,
        batch_row.dataset_key,
        batch_row.edition_years,
        batch_row.created_at,
        batch_row.cleaned_at;
$$;

CREATE OR REPLACE FUNCTION fn_synthetic_data_status()
RETURNS TABLE (
    has_active_batch BOOLEAN,
    active_batch_id BIGINT,
    dataset_key VARCHAR(80),
    edition_years SMALLINT[],
    created_at TIMESTAMPTZ,
    cleaned_at TIMESTAMPTZ,
    table_counts JSONB,
    total_rows BIGINT,
    history_batch_count BIGINT
)
LANGUAGE sql
SET search_path = world_cup, public
AS $$
    WITH active_batch AS (
        SELECT batch_row.id AS batch_id
        FROM synthetic_seed_batch batch_row
        WHERE batch_row.is_active = TRUE
        ORDER BY batch_row.id DESC
        LIMIT 1
    ),
    latest_batch AS (
        SELECT batch_row.id AS batch_id
        FROM synthetic_seed_batch batch_row
        ORDER BY batch_row.created_at DESC, batch_row.id DESC
        LIMIT 1
    ),
    selected_batch AS (
        SELECT COALESCE(
            (SELECT batch_id FROM active_batch),
            (SELECT batch_id FROM latest_batch)
        ) AS batch_id
    ),
    selected_summary AS (
        SELECT *
        FROM fn_internal_synthetic_batch_summary((SELECT batch_id FROM selected_batch))
    )
    SELECT
        COALESCE((SELECT TRUE FROM active_batch LIMIT 1), FALSE) AS has_active_batch,
        (SELECT batch_id FROM active_batch LIMIT 1) AS active_batch_id,
        selected_summary.dataset_key,
        COALESCE(selected_summary.edition_years, ARRAY[]::SMALLINT[]) AS edition_years,
        selected_summary.created_at,
        selected_summary.cleaned_at,
        COALESCE(selected_summary.table_counts, '{}'::JSONB) AS table_counts,
        COALESCE(selected_summary.total_rows, 0)::BIGINT AS total_rows,
        (SELECT COUNT(*)::BIGINT FROM synthetic_seed_batch) AS history_batch_count
    FROM (SELECT 1) singleton
    LEFT JOIN selected_summary ON TRUE;
$$;

CREATE OR REPLACE FUNCTION fn_seed_synthetic_data()
RETURNS TABLE (
    operation TEXT,
    status TEXT,
    active_batch_id BIGINT,
    edition_years SMALLINT[],
    table_counts JSONB,
    total_rows BIGINT,
    message TEXT
)
LANGUAGE plpgsql
SET search_path = world_cup, public
AS $synthetic$
DECLARE
    v_dataset_key CONSTANT VARCHAR(80) := 'canonical_v1';
    v_target_years CONSTANT SMALLINT[] := ARRAY[2034, 2038];
    v_batch_id BIGINT;
    v_existing_batch_id BIGINT;
    v_confederation_catalog CONSTANT JSONB := $json$
    [
        {"code": "SYNAMER", "name": "Synthetic Americas Confederation"},
        {"code": "SYNEURO", "name": "Synthetic European Confederation"},
        {"code": "SYNMENA", "name": "Synthetic Mediterranean Confederation"},
        {"code": "SYNPACI", "name": "Synthetic Pacific Confederation"},
        {"code": "SYNNORD", "name": "Synthetic Northern Confederation"},
        {"code": "SYNSOLA", "name": "Synthetic Solar Confederation"}
    ]
    $json$::JSONB;
    v_team_catalog CONSTANT JSONB := $json$
    [
        {"team_seq": 1, "confederation_code": "SYNAMER", "country_name": "Aurora Republic", "fifa_code": "AUR", "coach_name": "Adrian Mercer", "coach_birth_date": "1974-03-18"},
        {"team_seq": 2, "confederation_code": "SYNAMER", "country_name": "Borealis", "fifa_code": "BOR", "coach_name": "Mateo Calder", "coach_birth_date": "1972-11-02"},
        {"team_seq": 3, "confederation_code": "SYNAMER", "country_name": "Cascadia", "fifa_code": "CAS", "coach_name": "Elliot Navarro", "coach_birth_date": "1976-07-14"},
        {"team_seq": 4, "confederation_code": "SYNAMER", "country_name": "Duneshire", "fifa_code": "DUN", "coach_name": "Hugo Renn", "coach_birth_date": "1978-01-27"},
        {"team_seq": 5, "confederation_code": "SYNEURO", "country_name": "Estoria", "fifa_code": "EST", "coach_name": "Victor Salvi", "coach_birth_date": "1971-09-09"},
        {"team_seq": 6, "confederation_code": "SYNEURO", "country_name": "Fjordland", "fifa_code": "FJD", "coach_name": "Jonas Halberg", "coach_birth_date": "1975-05-21"},
        {"team_seq": 7, "confederation_code": "SYNEURO", "country_name": "Galewood", "fifa_code": "GLW", "coach_name": "Martin Keane", "coach_birth_date": "1977-04-11"},
        {"team_seq": 8, "confederation_code": "SYNEURO", "country_name": "Helvetia", "fifa_code": "HLV", "coach_name": "Sebastian Vogt", "coach_birth_date": "1973-12-06"},
        {"team_seq": 9, "confederation_code": "SYNMENA", "country_name": "Ivernia", "fifa_code": "IVE", "coach_name": "Luca Fiore", "coach_birth_date": "1970-08-03"},
        {"team_seq": 10, "confederation_code": "SYNMENA", "country_name": "Juniper", "fifa_code": "JNP", "coach_name": "Rafael Miro", "coach_birth_date": "1978-02-22"},
        {"team_seq": 11, "confederation_code": "SYNMENA", "country_name": "Kestrelia", "fifa_code": "KES", "coach_name": "Damian Soler", "coach_birth_date": "1974-06-15"},
        {"team_seq": 12, "confederation_code": "SYNMENA", "country_name": "Luminara", "fifa_code": "LUM", "coach_name": "Nico Varela", "coach_birth_date": "1976-10-10"},
        {"team_seq": 13, "confederation_code": "SYNPACI", "country_name": "Meridian", "fifa_code": "MRD", "coach_name": "Owen Hartwell", "coach_birth_date": "1972-04-01"},
        {"team_seq": 14, "confederation_code": "SYNPACI", "country_name": "Norvale", "fifa_code": "NRV", "coach_name": "Declan Moore", "coach_birth_date": "1971-07-29"},
        {"team_seq": 15, "confederation_code": "SYNPACI", "country_name": "Oceana", "fifa_code": "OCE", "coach_name": "Mason Reed", "coach_birth_date": "1979-01-13"},
        {"team_seq": 16, "confederation_code": "SYNPACI", "country_name": "Portovia", "fifa_code": "PTV", "coach_name": "Liam Soren", "coach_birth_date": "1977-09-30"},
        {"team_seq": 17, "confederation_code": "SYNNORD", "country_name": "Quinterra", "fifa_code": "QTR", "coach_name": "Thiago Arendt", "coach_birth_date": "1975-08-17"},
        {"team_seq": 18, "confederation_code": "SYNNORD", "country_name": "Rosaria", "fifa_code": "ROS", "coach_name": "Emilio Braga", "coach_birth_date": "1973-03-07"},
        {"team_seq": 19, "confederation_code": "SYNNORD", "country_name": "Solhaven", "fifa_code": "SLH", "coach_name": "Leo Corvin", "coach_birth_date": "1976-11-24"},
        {"team_seq": 20, "confederation_code": "SYNNORD", "country_name": "Tiberia", "fifa_code": "TIB", "coach_name": "Arturo Medeiros", "coach_birth_date": "1974-02-19"},
        {"team_seq": 21, "confederation_code": "SYNSOLA", "country_name": "Umbriel", "fifa_code": "UMB", "coach_name": "Dario Ventura", "coach_birth_date": "1972-05-09"},
        {"team_seq": 22, "confederation_code": "SYNSOLA", "country_name": "Valedon", "fifa_code": "VAL", "coach_name": "Caio Serrano", "coach_birth_date": "1977-06-27"},
        {"team_seq": 23, "confederation_code": "SYNSOLA", "country_name": "Westerdam", "fifa_code": "WDM", "coach_name": "Bruno Alencar", "coach_birth_date": "1978-12-15"},
        {"team_seq": 24, "confederation_code": "SYNSOLA", "country_name": "Zephyria", "fifa_code": "ZEP", "coach_name": "Ivan Delacroix", "coach_birth_date": "1971-10-31"}
    ]
    $json$::JSONB;
    v_referee_catalog CONSTANT JSONB := $json$
    [
        {"referee_seq": 1, "full_name": "Marco Ellison", "country_name": "Aurora Republic"},
        {"referee_seq": 2, "full_name": "Santiago Neri", "country_name": "Cascadia"},
        {"referee_seq": 3, "full_name": "Noah Kjellsen", "country_name": "Fjordland"},
        {"referee_seq": 4, "full_name": "Theo Marceau", "country_name": "Helvetia"},
        {"referee_seq": 5, "full_name": "Ruben Faris", "country_name": "Ivernia"},
        {"referee_seq": 6, "full_name": "Lorenzo Voss", "country_name": "Juniper"},
        {"referee_seq": 7, "full_name": "Callum Stride", "country_name": "Meridian"},
        {"referee_seq": 8, "full_name": "Aiden Sato", "country_name": "Norvale"},
        {"referee_seq": 9, "full_name": "Milan Ortega", "country_name": "Quinterra"},
        {"referee_seq": 10, "full_name": "Dylan Novak", "country_name": "Solhaven"},
        {"referee_seq": 11, "full_name": "Leandro Costa", "country_name": "Umbriel"},
        {"referee_seq": 12, "full_name": "Jonah Almeida", "country_name": "Westerdam"}
    ]
    $json$::JSONB;
    v_host_venue_catalog CONSTANT JSONB := $json$
    [
        {"edition_year": 2034, "city_name": "Cascade Bay", "stadium_name": "Cascade National Stadium", "capacity": 74200},
        {"edition_year": 2034, "city_name": "Verdant Point", "stadium_name": "Verdant Arena", "capacity": 68100},
        {"edition_year": 2034, "city_name": "Red Cedar", "stadium_name": "Red Cedar Park", "capacity": 65800},
        {"edition_year": 2034, "city_name": "High Timber", "stadium_name": "High Timber Field", "capacity": 62300},
        {"edition_year": 2038, "city_name": "Solaris", "stadium_name": "Solar Crown Stadium", "capacity": 76800},
        {"edition_year": 2038, "city_name": "Northreach", "stadium_name": "Northreach Grounds", "capacity": 69400},
        {"edition_year": 2038, "city_name": "Aureate", "stadium_name": "Aureate Arena", "capacity": 67100},
        {"edition_year": 2038, "city_name": "Larkspur", "stadium_name": "Larkspur Stadium", "capacity": 63900}
    ]
    $json$::JSONB;
    v_edition_team_catalog CONSTANT JSONB := $json$
    [
        {"edition_year": 2034, "group_letter": "A", "group_slot": 1, "team_code": "AUR", "final_rank": 1},
        {"edition_year": 2034, "group_letter": "A", "group_slot": 2, "team_code": "BOR", "final_rank": 5},
        {"edition_year": 2034, "group_letter": "A", "group_slot": 3, "team_code": "CAS", "final_rank": 9},
        {"edition_year": 2034, "group_letter": "A", "group_slot": 4, "team_code": "DUN", "final_rank": 13},
        {"edition_year": 2034, "group_letter": "B", "group_slot": 1, "team_code": "FJD", "final_rank": 4},
        {"edition_year": 2034, "group_letter": "B", "group_slot": 2, "team_code": "EST", "final_rank": 6},
        {"edition_year": 2034, "group_letter": "B", "group_slot": 3, "team_code": "HLV", "final_rank": 10},
        {"edition_year": 2034, "group_letter": "B", "group_slot": 4, "team_code": "GLW", "final_rank": 14},
        {"edition_year": 2034, "group_letter": "C", "group_slot": 1, "team_code": "IVE", "final_rank": 2},
        {"edition_year": 2034, "group_letter": "C", "group_slot": 2, "team_code": "JNP", "final_rank": 7},
        {"edition_year": 2034, "group_letter": "C", "group_slot": 3, "team_code": "KES", "final_rank": 11},
        {"edition_year": 2034, "group_letter": "C", "group_slot": 4, "team_code": "LUM", "final_rank": 15},
        {"edition_year": 2034, "group_letter": "D", "group_slot": 1, "team_code": "MRD", "final_rank": 3},
        {"edition_year": 2034, "group_letter": "D", "group_slot": 2, "team_code": "NRV", "final_rank": 8},
        {"edition_year": 2034, "group_letter": "D", "group_slot": 3, "team_code": "OCE", "final_rank": 12},
        {"edition_year": 2034, "group_letter": "D", "group_slot": 4, "team_code": "PTV", "final_rank": 16},
        {"edition_year": 2038, "group_letter": "A", "group_slot": 1, "team_code": "AUR", "final_rank": 2},
        {"edition_year": 2038, "group_letter": "A", "group_slot": 2, "team_code": "BOR", "final_rank": 6},
        {"edition_year": 2038, "group_letter": "A", "group_slot": 3, "team_code": "QTR", "final_rank": 9},
        {"edition_year": 2038, "group_letter": "A", "group_slot": 4, "team_code": "ROS", "final_rank": 13},
        {"edition_year": 2038, "group_letter": "B", "group_slot": 1, "team_code": "FJD", "final_rank": 3},
        {"edition_year": 2038, "group_letter": "B", "group_slot": 2, "team_code": "HLV", "final_rank": 5},
        {"edition_year": 2038, "group_letter": "B", "group_slot": 3, "team_code": "SLH", "final_rank": 10},
        {"edition_year": 2038, "group_letter": "B", "group_slot": 4, "team_code": "TIB", "final_rank": 14},
        {"edition_year": 2038, "group_letter": "C", "group_slot": 1, "team_code": "IVE", "final_rank": 1},
        {"edition_year": 2038, "group_letter": "C", "group_slot": 2, "team_code": "JNP", "final_rank": 7},
        {"edition_year": 2038, "group_letter": "C", "group_slot": 3, "team_code": "UMB", "final_rank": 11},
        {"edition_year": 2038, "group_letter": "C", "group_slot": 4, "team_code": "VAL", "final_rank": 15},
        {"edition_year": 2038, "group_letter": "D", "group_slot": 1, "team_code": "MRD", "final_rank": 4},
        {"edition_year": 2038, "group_letter": "D", "group_slot": 2, "team_code": "NRV", "final_rank": 8},
        {"edition_year": 2038, "group_letter": "D", "group_slot": 3, "team_code": "WDM", "final_rank": 12},
        {"edition_year": 2038, "group_letter": "D", "group_slot": 4, "team_code": "ZEP", "final_rank": 16}
    ]
    $json$::JSONB;
    v_knockout_catalog CONSTANT JSONB := $json$
    [
        {"edition_year": 2034, "phase_code": "QUARTERFINAL", "kickoff_at": "2034-06-28 16:00:00", "stadium_name": "Cascade National Stadium", "home_slot_ref": "A1", "away_slot_ref": "B2", "winner_slot_ref": "A1", "home_score": 2, "away_score": 1, "home_extra_score": 0, "away_extra_score": 0, "home_penalty_score": null, "away_penalty_score": null},
        {"edition_year": 2034, "phase_code": "QUARTERFINAL", "kickoff_at": "2034-06-28 20:00:00", "stadium_name": "Verdant Arena", "home_slot_ref": "C1", "away_slot_ref": "D2", "winner_slot_ref": "C1", "home_score": 1, "away_score": 0, "home_extra_score": 0, "away_extra_score": 0, "home_penalty_score": null, "away_penalty_score": null},
        {"edition_year": 2034, "phase_code": "QUARTERFINAL", "kickoff_at": "2034-06-29 16:00:00", "stadium_name": "Red Cedar Park", "home_slot_ref": "B1", "away_slot_ref": "A2", "winner_slot_ref": "B1", "home_score": 1, "away_score": 1, "home_extra_score": 1, "away_extra_score": 0, "home_penalty_score": null, "away_penalty_score": null},
        {"edition_year": 2034, "phase_code": "QUARTERFINAL", "kickoff_at": "2034-06-29 20:00:00", "stadium_name": "High Timber Field", "home_slot_ref": "D1", "away_slot_ref": "C2", "winner_slot_ref": "D1", "home_score": 0, "away_score": 0, "home_extra_score": 0, "away_extra_score": 0, "home_penalty_score": 4, "away_penalty_score": 3},
        {"edition_year": 2034, "phase_code": "SEMIFINAL", "kickoff_at": "2034-07-03 19:00:00", "stadium_name": "Cascade National Stadium", "home_slot_ref": "A1", "away_slot_ref": "B1", "winner_slot_ref": "A1", "home_score": 2, "away_score": 0, "home_extra_score": 0, "away_extra_score": 0, "home_penalty_score": null, "away_penalty_score": null},
        {"edition_year": 2034, "phase_code": "SEMIFINAL", "kickoff_at": "2034-07-04 19:00:00", "stadium_name": "Verdant Arena", "home_slot_ref": "C1", "away_slot_ref": "D1", "winner_slot_ref": "C1", "home_score": 1, "away_score": 1, "home_extra_score": 0, "away_extra_score": 0, "home_penalty_score": 5, "away_penalty_score": 4},
        {"edition_year": 2034, "phase_code": "THIRD_PLACE", "kickoff_at": "2034-07-07 17:00:00", "stadium_name": "Red Cedar Park", "home_slot_ref": "B1", "away_slot_ref": "D1", "winner_slot_ref": "D1", "home_score": 1, "away_score": 2, "home_extra_score": 0, "away_extra_score": 0, "home_penalty_score": null, "away_penalty_score": null},
        {"edition_year": 2034, "phase_code": "FINAL", "kickoff_at": "2034-07-08 18:00:00", "stadium_name": "Cascade National Stadium", "home_slot_ref": "A1", "away_slot_ref": "C1", "winner_slot_ref": "A1", "home_score": 1, "away_score": 1, "home_extra_score": 1, "away_extra_score": 1, "home_penalty_score": 4, "away_penalty_score": 3},
        {"edition_year": 2038, "phase_code": "QUARTERFINAL", "kickoff_at": "2038-07-01 16:00:00", "stadium_name": "Solar Crown Stadium", "home_slot_ref": "A1", "away_slot_ref": "B2", "winner_slot_ref": "A1", "home_score": 2, "away_score": 0, "home_extra_score": 0, "away_extra_score": 0, "home_penalty_score": null, "away_penalty_score": null},
        {"edition_year": 2038, "phase_code": "QUARTERFINAL", "kickoff_at": "2038-07-01 20:00:00", "stadium_name": "Northreach Grounds", "home_slot_ref": "C1", "away_slot_ref": "D2", "winner_slot_ref": "C1", "home_score": 2, "away_score": 1, "home_extra_score": 0, "away_extra_score": 0, "home_penalty_score": null, "away_penalty_score": null},
        {"edition_year": 2038, "phase_code": "QUARTERFINAL", "kickoff_at": "2038-07-02 16:00:00", "stadium_name": "Aureate Arena", "home_slot_ref": "B1", "away_slot_ref": "A2", "winner_slot_ref": "B1", "home_score": 1, "away_score": 0, "home_extra_score": 0, "away_extra_score": 0, "home_penalty_score": null, "away_penalty_score": null},
        {"edition_year": 2038, "phase_code": "QUARTERFINAL", "kickoff_at": "2038-07-02 20:00:00", "stadium_name": "Larkspur Stadium", "home_slot_ref": "D1", "away_slot_ref": "C2", "winner_slot_ref": "D1", "home_score": 1, "away_score": 1, "home_extra_score": 1, "away_extra_score": 0, "home_penalty_score": null, "away_penalty_score": null},
        {"edition_year": 2038, "phase_code": "SEMIFINAL", "kickoff_at": "2038-07-06 19:00:00", "stadium_name": "Solar Crown Stadium", "home_slot_ref": "A1", "away_slot_ref": "B1", "winner_slot_ref": "A1", "home_score": 1, "away_score": 0, "home_extra_score": 0, "away_extra_score": 0, "home_penalty_score": null, "away_penalty_score": null},
        {"edition_year": 2038, "phase_code": "SEMIFINAL", "kickoff_at": "2038-07-07 19:00:00", "stadium_name": "Northreach Grounds", "home_slot_ref": "C1", "away_slot_ref": "D1", "winner_slot_ref": "C1", "home_score": 2, "away_score": 1, "home_extra_score": 0, "away_extra_score": 0, "home_penalty_score": null, "away_penalty_score": null},
        {"edition_year": 2038, "phase_code": "THIRD_PLACE", "kickoff_at": "2038-07-10 17:00:00", "stadium_name": "Aureate Arena", "home_slot_ref": "B1", "away_slot_ref": "D1", "winner_slot_ref": "B1", "home_score": 2, "away_score": 0, "home_extra_score": 0, "away_extra_score": 0, "home_penalty_score": null, "away_penalty_score": null},
        {"edition_year": 2038, "phase_code": "FINAL", "kickoff_at": "2038-07-11 18:00:00", "stadium_name": "Solar Crown Stadium", "home_slot_ref": "A1", "away_slot_ref": "C1", "winner_slot_ref": "C1", "home_score": 0, "away_score": 2, "home_extra_score": 0, "away_extra_score": 0, "home_penalty_score": null, "away_penalty_score": null}
    ]
    $json$::JSONB;
    v_first_names CONSTANT TEXT[] := ARRAY[
        'Aiden', 'Luca', 'Mateo', 'Jonah', 'Theo', 'Rafael', 'Nico', 'Elias', 'Milan', 'Dario',
        'Caio', 'Bruno', 'Adrian', 'Leo', 'Victor', 'Noah', 'Callum', 'Owen', 'Sebastian', 'Thiago',
        'Emilio', 'Ivan', 'Ruben', 'Mason', 'Declan', 'Arturo', 'Martin', 'Santiago', 'Lorenzo', 'Dylan',
        'Marco', 'Damian', 'Hugo', 'Liam', 'Jordan', 'Felix'
    ];
    v_last_names_a CONSTANT TEXT[] := ARRAY[
        'Valente', 'Rossi', 'Keane', 'Moreau', 'Santos', 'Mercer', 'Navarro', 'Halberg', 'Varela', 'Serrano',
        'Almeida', 'Costa', 'Miro', 'Reed', 'Corvin', 'Novak', 'Stride', 'Faris', 'Braga', 'Delacroix',
        'Arendt', 'Voss', 'Ortega', 'Fiore', 'Hartwell', 'Moore', 'Ventura', 'Marin', 'Calder', 'Soler',
        'Kjellsen', 'Renn', 'Salvi', 'Vogt', 'Medeiros', 'Alencar'
    ];
    v_last_names_b CONSTANT TEXT[] := ARRAY[
        'Silva', 'Laurent', 'Barlow', 'Pereira', 'Cervantes', 'Lindholm', 'Romero', 'Duarte', 'Castro', 'Bennett',
        'Ferreira', 'Bastos', 'Paredes', 'Molina', 'Ribeiro', 'Harrison', 'Lucero', 'Mendes', 'Fidalgo', 'Tavares',
        'Renard', 'Azevedo', 'Cardoso', 'Esteves', 'Muniz', 'Dominguez', 'Torres', 'Foster', 'Aguiar', 'Siqueira',
        'Moraes', 'Barbosa', 'Leite', 'Vasconcelos', 'Guerra', 'Campos'
    ];
BEGIN
    PERFORM fn_internal_acquire_synthetic_seed_lock();

    SELECT batch_row.id
    INTO v_existing_batch_id
    FROM synthetic_seed_batch batch_row
    WHERE batch_row.is_active = TRUE
    ORDER BY batch_row.id DESC
    LIMIT 1;

    IF v_existing_batch_id IS NOT NULL THEN
        RETURN QUERY
        SELECT
            'populate'::TEXT AS operation,
            'already_seeded'::TEXT AS status,
            summary_row.batch_id AS active_batch_id,
            summary_row.edition_years,
            summary_row.table_counts,
            summary_row.total_rows,
            'Synthetic dataset is already active.'::TEXT AS message
        FROM fn_internal_synthetic_batch_summary(v_existing_batch_id) summary_row;
        RETURN;
    END IF;

    IF EXISTS (
        SELECT 1
        FROM world_cup_edition edition_row
        WHERE edition_row.year = ANY (v_target_years)
    ) THEN
        RAISE EXCEPTION
            'Cannot seed synthetic data because one or more target edition years (%) already exist outside the synthetic registry.',
            array_to_string(v_target_years, ', ');
    END IF;

    IF EXISTS (
        SELECT 1
        FROM competition_phase phase_row
        WHERE phase_row.code IN ('GROUP_STAGE', 'QUARTERFINAL', 'SEMIFINAL', 'THIRD_PLACE', 'FINAL')
    ) THEN
        RAISE EXCEPTION
            'Cannot seed synthetic data because one or more synthetic competition phases already exist.';
    END IF;

    INSERT INTO synthetic_seed_batch (dataset_key, edition_years)
    VALUES (v_dataset_key, v_target_years)
    RETURNING id INTO v_batch_id;

    WITH confederation_seed AS (
        SELECT *
        FROM jsonb_to_recordset(v_confederation_catalog) AS confederation_seed(
            code TEXT,
            name TEXT
        )
    ),
    inserted AS (
        INSERT INTO confederation (code, name)
        SELECT confederation_seed.code, confederation_seed.name
        FROM confederation_seed
        RETURNING id
    )
    INSERT INTO synthetic_seed_registry (batch_id, table_name, primary_key)
    SELECT v_batch_id, 'confederation', jsonb_build_object('id', inserted.id)
    FROM inserted;

    WITH team_seed AS (
        SELECT *
        FROM jsonb_to_recordset(v_team_catalog) AS team_seed(
            team_seq INTEGER,
            confederation_code TEXT,
            country_name TEXT,
            fifa_code CHAR(3),
            coach_name TEXT,
            coach_birth_date DATE
        )
    ),
    inserted AS (
        INSERT INTO country (name, fifa_code, confederation_id)
        SELECT
            team_seed.country_name,
            team_seed.fifa_code,
            confederation_row.id
        FROM team_seed
        JOIN confederation confederation_row
            ON confederation_row.code = team_seed.confederation_code
        RETURNING id
    )
    INSERT INTO synthetic_seed_registry (batch_id, table_name, primary_key)
    SELECT v_batch_id, 'country', jsonb_build_object('id', inserted.id)
    FROM inserted;

    WITH team_seed AS (
        SELECT *
        FROM jsonb_to_recordset(v_team_catalog) AS team_seed(
            team_seq INTEGER,
            confederation_code TEXT,
            country_name TEXT,
            fifa_code CHAR(3),
            coach_name TEXT,
            coach_birth_date DATE
        )
    ),
    inserted AS (
        INSERT INTO team (name, fifa_code, country_id)
        SELECT
            team_seed.country_name,
            team_seed.fifa_code,
            country_row.id
        FROM team_seed
        JOIN country country_row ON country_row.name = team_seed.country_name
        RETURNING id
    )
    INSERT INTO synthetic_seed_registry (batch_id, table_name, primary_key)
    SELECT v_batch_id, 'team', jsonb_build_object('id', inserted.id)
    FROM inserted;

    WITH team_seed AS (
        SELECT *
        FROM jsonb_to_recordset(v_team_catalog) AS team_seed(
            team_seq INTEGER,
            confederation_code TEXT,
            country_name TEXT,
            fifa_code CHAR(3),
            coach_name TEXT,
            coach_birth_date DATE
        )
    ),
    inserted AS (
        INSERT INTO coach (full_name, birth_date, country_id)
        SELECT
            team_seed.coach_name,
            team_seed.coach_birth_date,
            country_row.id
        FROM team_seed
        JOIN country country_row ON country_row.name = team_seed.country_name
        RETURNING id
    )
    INSERT INTO synthetic_seed_registry (batch_id, table_name, primary_key)
    SELECT v_batch_id, 'coach', jsonb_build_object('id', inserted.id)
    FROM inserted;

    WITH referee_seed AS (
        SELECT *
        FROM jsonb_to_recordset(v_referee_catalog) AS referee_seed(
            referee_seq INTEGER,
            full_name TEXT,
            country_name TEXT
        )
    ),
    inserted AS (
        INSERT INTO referee (full_name, country_id)
        SELECT
            referee_seed.full_name,
            country_row.id
        FROM referee_seed
        JOIN country country_row ON country_row.name = referee_seed.country_name
        RETURNING id
    )
    INSERT INTO synthetic_seed_registry (batch_id, table_name, primary_key)
    SELECT v_batch_id, 'referee', jsonb_build_object('id', inserted.id)
    FROM inserted;

    WITH team_seed AS (
        SELECT *
        FROM jsonb_to_recordset(v_team_catalog) AS team_seed(
            team_seq INTEGER,
            confederation_code TEXT,
            country_name TEXT,
            fifa_code CHAR(3),
            coach_name TEXT,
            coach_birth_date DATE
        )
    ),
    player_seed AS (
        SELECT
            team_seed.team_seq,
            squad_slot,
            (
                v_first_names[1 + mod(team_seed.team_seq + squad_slot - 2, array_length(v_first_names, 1))]
                || ' '
                || v_last_names_a[1 + mod(team_seed.team_seq * 2 + squad_slot - 3, array_length(v_last_names_a, 1))]
                || ' '
                || v_last_names_b[1 + mod(team_seed.team_seq * 3 + squad_slot - 4, array_length(v_last_names_b, 1))]
            ) AS full_name,
            (DATE '1987-01-01' + ((team_seed.team_seq - 1) * 37 + squad_slot * 29)) AS birth_date,
            CASE
                WHEN squad_slot IN (1, 12) THEN 'Goalkeeper'
                WHEN squad_slot IN (2, 3, 4, 5, 13) THEN 'Defender'
                WHEN squad_slot IN (6, 7, 8, 14) THEN 'Midfielder'
                ELSE 'Forward'
            END AS primary_position,
            team_seed.country_name
        FROM team_seed
        CROSS JOIN generate_series(1, 15) AS squad_slot(squad_slot)
    ),
    inserted AS (
        INSERT INTO player (full_name, birth_date, primary_position, country_of_birth_id)
        SELECT
            player_seed.full_name,
            player_seed.birth_date,
            player_seed.primary_position,
            country_row.id
        FROM player_seed
        JOIN country country_row ON country_row.name = player_seed.country_name
        RETURNING id
    )
    INSERT INTO synthetic_seed_registry (batch_id, table_name, primary_key)
    SELECT v_batch_id, 'player', jsonb_build_object('id', inserted.id)
    FROM inserted;

    WITH edition_seed AS (
        SELECT *
        FROM (VALUES
            (2034::SMALLINT, 'Cascadia'::TEXT, DATE '2034-06-10', DATE '2034-07-08'),
            (2038::SMALLINT, 'Solhaven'::TEXT, DATE '2038-06-14', DATE '2038-07-11')
        ) AS edition_seed(edition_year, host_country_name, start_date, end_date)
    ),
    inserted AS (
        INSERT INTO world_cup_edition (year, host_country_id, start_date, end_date)
        SELECT
            edition_seed.edition_year,
            country_row.id,
            edition_seed.start_date,
            edition_seed.end_date
        FROM edition_seed
        JOIN country country_row ON country_row.name = edition_seed.host_country_name
        RETURNING id
    )
    INSERT INTO synthetic_seed_registry (batch_id, table_name, primary_key)
    SELECT v_batch_id, 'world_cup_edition', jsonb_build_object('id', inserted.id)
    FROM inserted;

    WITH venue_seed AS (
        SELECT *
        FROM jsonb_to_recordset(v_host_venue_catalog) AS venue_seed(
            edition_year SMALLINT,
            city_name TEXT,
            stadium_name TEXT,
            capacity INTEGER
        )
    ),
    edition_host_seed AS (
        SELECT
            venue_seed.city_name,
            edition_row.host_country_id AS country_id
        FROM venue_seed
        JOIN world_cup_edition edition_row ON edition_row.year = venue_seed.edition_year
    ),
    inserted AS (
        INSERT INTO host_city (name, country_id)
        SELECT DISTINCT
            edition_host_seed.city_name,
            edition_host_seed.country_id
        FROM edition_host_seed
        RETURNING id
    )
    INSERT INTO synthetic_seed_registry (batch_id, table_name, primary_key)
    SELECT v_batch_id, 'host_city', jsonb_build_object('id', inserted.id)
    FROM inserted;

    WITH venue_seed AS (
        SELECT *
        FROM jsonb_to_recordset(v_host_venue_catalog) AS venue_seed(
            edition_year SMALLINT,
            city_name TEXT,
            stadium_name TEXT,
            capacity INTEGER
        )
    ),
    inserted AS (
        INSERT INTO stadium (name, host_city_id, capacity)
        SELECT
            venue_seed.stadium_name,
            host_city_row.id,
            venue_seed.capacity
        FROM venue_seed
        JOIN world_cup_edition edition_row ON edition_row.year = venue_seed.edition_year
        JOIN host_city host_city_row
            ON host_city_row.name = venue_seed.city_name
           AND host_city_row.country_id = edition_row.host_country_id
        RETURNING id
    )
    INSERT INTO synthetic_seed_registry (batch_id, table_name, primary_key)
    SELECT v_batch_id, 'stadium', jsonb_build_object('id', inserted.id)
    FROM inserted;

    WITH venue_seed AS (
        SELECT *
        FROM jsonb_to_recordset(v_host_venue_catalog) AS venue_seed(
            edition_year SMALLINT,
            city_name TEXT,
            stadium_name TEXT,
            capacity INTEGER
        )
    ),
    inserted AS (
        INSERT INTO edition_host_city (edition_id, host_city_id)
        SELECT
            edition_row.id,
            host_city_row.id
        FROM venue_seed
        JOIN world_cup_edition edition_row ON edition_row.year = venue_seed.edition_year
        JOIN host_city host_city_row
            ON host_city_row.name = venue_seed.city_name
           AND host_city_row.country_id = edition_row.host_country_id
        RETURNING edition_id, host_city_id
    )
    INSERT INTO synthetic_seed_registry (batch_id, table_name, primary_key)
    SELECT
        v_batch_id,
        'edition_host_city',
        jsonb_build_object(
            'edition_id', inserted.edition_id,
            'host_city_id', inserted.host_city_id
        )
    FROM inserted;

    WITH phase_seed AS (
        SELECT *
        FROM (VALUES
            ('GROUP_STAGE'::TEXT, 'Group Stage'::TEXT, 'GROUP'::phase_kind, 1::SMALLINT, TRUE),
            ('QUARTERFINAL'::TEXT, 'Quarterfinal'::TEXT, 'KNOCKOUT'::phase_kind, 2::SMALLINT, FALSE),
            ('SEMIFINAL'::TEXT, 'Semifinal'::TEXT, 'KNOCKOUT'::phase_kind, 3::SMALLINT, FALSE),
            ('THIRD_PLACE'::TEXT, 'Third Place Match'::TEXT, 'PLACEMENT'::phase_kind, 4::SMALLINT, FALSE),
            ('FINAL'::TEXT, 'Final'::TEXT, 'KNOCKOUT'::phase_kind, 5::SMALLINT, FALSE)
        ) AS phase_seed(code, display_name, phase_kind, sort_order, allows_draw)
    ),
    inserted AS (
        INSERT INTO competition_phase (code, display_name, phase_kind, sort_order, allows_draw)
        SELECT
            phase_seed.code,
            phase_seed.display_name,
            phase_seed.phase_kind,
            phase_seed.sort_order,
            phase_seed.allows_draw
        FROM phase_seed
        RETURNING id
    )
    INSERT INTO synthetic_seed_registry (batch_id, table_name, primary_key)
    SELECT v_batch_id, 'competition_phase', jsonb_build_object('id', inserted.id)
    FROM inserted;

    WITH edition_seed AS (
        SELECT *
        FROM (VALUES
            (2034::SMALLINT),
            (2038::SMALLINT)
        ) AS edition_seed(edition_year)
    ),
    phase_seed AS (
        SELECT *
        FROM (VALUES
            ('GROUP_STAGE'::TEXT),
            ('QUARTERFINAL'::TEXT),
            ('SEMIFINAL'::TEXT),
            ('THIRD_PLACE'::TEXT),
            ('FINAL'::TEXT)
        ) AS phase_seed(phase_code)
    ),
    inserted AS (
        INSERT INTO edition_phase (edition_id, phase_id, label, stage_order)
        SELECT
            edition_row.id,
            phase_row.id,
            edition_row.year::TEXT || ' ' || phase_row.display_name,
            phase_row.sort_order
        FROM edition_seed
        JOIN world_cup_edition edition_row ON edition_row.year = edition_seed.edition_year
        JOIN phase_seed ON TRUE
        JOIN competition_phase phase_row ON phase_row.code = phase_seed.phase_code
        RETURNING id, edition_id
    )
    INSERT INTO synthetic_seed_registry (batch_id, table_name, primary_key)
    SELECT
        v_batch_id,
        'edition_phase',
        jsonb_build_object(
            'id', inserted.id,
            'edition_id', inserted.edition_id
        )
    FROM inserted;

    WITH edition_team_seed AS (
        SELECT *
        FROM jsonb_to_recordset(v_edition_team_catalog) AS edition_team_seed(
            edition_year SMALLINT,
            group_letter CHAR(1),
            group_slot SMALLINT,
            team_code CHAR(3),
            final_rank SMALLINT
        )
    ),
    inserted AS (
        INSERT INTO team_group (edition_id, group_letter)
        SELECT DISTINCT
            edition_row.id,
            edition_team_seed.group_letter
        FROM edition_team_seed
        JOIN world_cup_edition edition_row ON edition_row.year = edition_team_seed.edition_year
        RETURNING id, edition_id
    )
    INSERT INTO synthetic_seed_registry (batch_id, table_name, primary_key)
    SELECT
        v_batch_id,
        'team_group',
        jsonb_build_object(
            'id', inserted.id,
            'edition_id', inserted.edition_id
        )
    FROM inserted;

    WITH edition_team_seed AS (
        SELECT *
        FROM jsonb_to_recordset(v_edition_team_catalog) AS edition_team_seed(
            edition_year SMALLINT,
            group_letter CHAR(1),
            group_slot SMALLINT,
            team_code CHAR(3),
            final_rank SMALLINT
        )
    ),
    inserted AS (
        INSERT INTO edition_team (edition_id, team_id, coach_id, group_id, final_rank)
        SELECT
            edition_row.id,
            team_row.id,
            coach_row.id,
            team_group_row.id,
            edition_team_seed.final_rank
        FROM edition_team_seed
        JOIN world_cup_edition edition_row ON edition_row.year = edition_team_seed.edition_year
        JOIN team team_row ON team_row.fifa_code = edition_team_seed.team_code
        JOIN coach coach_row ON coach_row.full_name = (
            SELECT team_seed.coach_name
            FROM jsonb_to_recordset(v_team_catalog) AS team_seed(
                team_seq INTEGER,
                confederation_code TEXT,
                country_name TEXT,
                fifa_code CHAR(3),
                coach_name TEXT,
                coach_birth_date DATE
            )
            WHERE team_seed.fifa_code = edition_team_seed.team_code
        )
        JOIN team_group team_group_row
            ON team_group_row.edition_id = edition_row.id
           AND team_group_row.group_letter = edition_team_seed.group_letter
        RETURNING id, edition_id, team_id
    )
    INSERT INTO synthetic_seed_registry (batch_id, table_name, primary_key)
    SELECT
        v_batch_id,
        'edition_team',
        jsonb_build_object('id', inserted.id)
    FROM inserted;

    WITH team_seed AS (
        SELECT *
        FROM jsonb_to_recordset(v_team_catalog) AS team_seed(
            team_seq INTEGER,
            confederation_code TEXT,
            country_name TEXT,
            fifa_code CHAR(3),
            coach_name TEXT,
            coach_birth_date DATE
        )
    ),
    player_seed AS (
        SELECT
            team_seed.fifa_code,
            squad_slot::SMALLINT AS shirt_number,
            (
                v_first_names[1 + mod(team_seed.team_seq + squad_slot - 2, array_length(v_first_names, 1))]
                || ' '
                || v_last_names_a[1 + mod(team_seed.team_seq * 2 + squad_slot - 3, array_length(v_last_names_a, 1))]
                || ' '
                || v_last_names_b[1 + mod(team_seed.team_seq * 3 + squad_slot - 4, array_length(v_last_names_b, 1))]
            ) AS full_name,
            (DATE '1987-01-01' + ((team_seed.team_seq - 1) * 37 + squad_slot * 29)) AS birth_date,
            CASE
                WHEN squad_slot IN (1, 12) THEN 'Goalkeeper'
                WHEN squad_slot IN (2, 3, 4, 5, 13) THEN 'Defender'
                WHEN squad_slot IN (6, 7, 8, 14) THEN 'Midfielder'
                ELSE 'Forward'
            END AS primary_position
        FROM team_seed
        CROSS JOIN generate_series(1, 15) AS squad_slot(squad_slot)
    ),
    edition_team_seed AS (
        SELECT *
        FROM jsonb_to_recordset(v_edition_team_catalog) AS edition_team_seed(
            edition_year SMALLINT,
            group_letter CHAR(1),
            group_slot SMALLINT,
            team_code CHAR(3),
            final_rank SMALLINT
        )
    ),
    inserted AS (
        INSERT INTO team_call_up (
            edition_id,
            team_id,
            player_id,
            shirt_number,
            squad_role,
            primary_position,
            is_captain
        )
        SELECT
            edition_row.id,
            team_row.id,
            player_row.id,
            player_seed.shirt_number,
            'PLAYER',
            player_seed.primary_position,
            player_seed.shirt_number = 10
        FROM edition_team_seed
        JOIN world_cup_edition edition_row ON edition_row.year = edition_team_seed.edition_year
        JOIN team team_row ON team_row.fifa_code = edition_team_seed.team_code
        JOIN player_seed ON player_seed.fifa_code = edition_team_seed.team_code
        JOIN player player_row
            ON player_row.full_name = player_seed.full_name
           AND player_row.birth_date = player_seed.birth_date
        RETURNING edition_id, team_id, player_id
    )
    INSERT INTO synthetic_seed_registry (batch_id, table_name, primary_key)
    SELECT
        v_batch_id,
        'team_call_up',
        jsonb_build_object(
            'edition_id', inserted.edition_id,
            'team_id', inserted.team_id,
            'player_id', inserted.player_id
        )
    FROM inserted;

    WITH edition_team_seed AS (
        SELECT *
        FROM jsonb_to_recordset(v_edition_team_catalog) AS edition_team_seed(
            edition_year SMALLINT,
            group_letter CHAR(1),
            group_slot SMALLINT,
            team_code CHAR(3),
            final_rank SMALLINT
        )
    ),
    group_fixture_template AS (
        SELECT *
        FROM (VALUES
            (1::SMALLINT, 1::SMALLINT, 1::SMALLINT, 2::SMALLINT, 2::SMALLINT, 0::SMALLINT),
            (1::SMALLINT, 2::SMALLINT, 3::SMALLINT, 4::SMALLINT, 2::SMALLINT, 1::SMALLINT),
            (2::SMALLINT, 1::SMALLINT, 1::SMALLINT, 3::SMALLINT, 1::SMALLINT, 0::SMALLINT),
            (2::SMALLINT, 2::SMALLINT, 2::SMALLINT, 4::SMALLINT, 2::SMALLINT, 1::SMALLINT),
            (3::SMALLINT, 1::SMALLINT, 1::SMALLINT, 4::SMALLINT, 1::SMALLINT, 1::SMALLINT),
            (3::SMALLINT, 2::SMALLINT, 2::SMALLINT, 3::SMALLINT, 2::SMALLINT, 0::SMALLINT)
        ) AS group_fixture_template(match_day, fixture_order, home_slot, away_slot, home_score, away_score)
    ),
    group_index_seed AS (
        SELECT *
        FROM (VALUES
            ('A'::CHAR(1), 1::INTEGER),
            ('B'::CHAR(1), 2::INTEGER),
            ('C'::CHAR(1), 3::INTEGER),
            ('D'::CHAR(1), 4::INTEGER)
        ) AS group_index_seed(group_letter, group_index)
    ),
    venue_slot_seed AS (
        SELECT *
        FROM (VALUES
            (2034::SMALLINT, 1::INTEGER, 'Cascade National Stadium'::TEXT),
            (2034::SMALLINT, 2::INTEGER, 'Verdant Arena'::TEXT),
            (2034::SMALLINT, 3::INTEGER, 'Red Cedar Park'::TEXT),
            (2034::SMALLINT, 4::INTEGER, 'High Timber Field'::TEXT),
            (2038::SMALLINT, 1::INTEGER, 'Solar Crown Stadium'::TEXT),
            (2038::SMALLINT, 2::INTEGER, 'Northreach Grounds'::TEXT),
            (2038::SMALLINT, 3::INTEGER, 'Aureate Arena'::TEXT),
            (2038::SMALLINT, 4::INTEGER, 'Larkspur Stadium'::TEXT)
        ) AS venue_slot_seed(edition_year, venue_slot, stadium_name)
    ),
    group_match_seed AS (
        SELECT
            edition_row.id AS edition_id,
            edition_phase_row.id AS edition_phase_id,
            team_group_row.id AS group_id,
            stadium_row.id AS stadium_id,
            (
                edition_row.start_date::TIMESTAMP
                + ((group_fixture_template.match_day - 1) * 4 + group_index_seed.group_index - 1) * INTERVAL '1 day'
                + CASE
                    WHEN group_fixture_template.fixture_order = 1 THEN TIME '16:00'
                    ELSE TIME '20:00'
                END
            ) AS kickoff_at,
            home_team_row.team_id AS home_team_id,
            away_team_row.team_id AS away_team_id,
            CASE
                WHEN group_fixture_template.home_score > group_fixture_template.away_score THEN home_team_row.team_id
                WHEN group_fixture_template.away_score > group_fixture_template.home_score THEN away_team_row.team_id
                ELSE NULL
            END AS winner_team_id,
            group_fixture_template.home_score,
            group_fixture_template.away_score,
            0::SMALLINT AS home_extra_score,
            0::SMALLINT AS away_extra_score,
            NULL::SMALLINT AS home_penalty_score,
            NULL::SMALLINT AS away_penalty_score,
            group_fixture_template.match_day
        FROM group_fixture_template
        JOIN group_index_seed ON TRUE
        JOIN world_cup_edition edition_row ON edition_row.year IN (2034, 2038)
        JOIN edition_phase edition_phase_row
            ON edition_phase_row.edition_id = edition_row.id
        JOIN competition_phase phase_row
            ON phase_row.id = edition_phase_row.phase_id
           AND phase_row.code = 'GROUP_STAGE'
        JOIN team_group team_group_row
            ON team_group_row.edition_id = edition_row.id
           AND team_group_row.group_letter = group_index_seed.group_letter
        JOIN edition_team_seed home_seed
            ON home_seed.edition_year = edition_row.year
           AND home_seed.group_letter = group_index_seed.group_letter
           AND home_seed.group_slot = group_fixture_template.home_slot
        JOIN edition_team_seed away_seed
            ON away_seed.edition_year = edition_row.year
           AND away_seed.group_letter = group_index_seed.group_letter
           AND away_seed.group_slot = group_fixture_template.away_slot
        JOIN edition_team home_team_row
            ON home_team_row.edition_id = edition_row.id
        JOIN team home_team_catalog ON home_team_catalog.id = home_team_row.team_id
           AND home_team_catalog.fifa_code = home_seed.team_code
        JOIN edition_team away_team_row
            ON away_team_row.edition_id = edition_row.id
        JOIN team away_team_catalog ON away_team_catalog.id = away_team_row.team_id
           AND away_team_catalog.fifa_code = away_seed.team_code
        JOIN venue_slot_seed
            ON venue_slot_seed.edition_year = edition_row.year
           AND venue_slot_seed.venue_slot = group_index_seed.group_index
        JOIN stadium stadium_row ON stadium_row.name = venue_slot_seed.stadium_name
    ),
    knockout_seed AS (
        SELECT *
        FROM jsonb_to_recordset(v_knockout_catalog) AS knockout_seed(
            edition_year SMALLINT,
            phase_code TEXT,
            kickoff_at TIMESTAMP,
            stadium_name TEXT,
            home_slot_ref TEXT,
            away_slot_ref TEXT,
            winner_slot_ref TEXT,
            home_score SMALLINT,
            away_score SMALLINT,
            home_extra_score SMALLINT,
            away_extra_score SMALLINT,
            home_penalty_score SMALLINT,
            away_penalty_score SMALLINT
        )
    ),
    knockout_match_seed AS (
        SELECT
            edition_row.id AS edition_id,
            edition_phase_row.id AS edition_phase_id,
            NULL::BIGINT AS group_id,
            stadium_row.id AS stadium_id,
            knockout_seed.kickoff_at,
            home_team_row.team_id AS home_team_id,
            away_team_row.team_id AS away_team_id,
            winner_team_row.team_id AS winner_team_id,
            knockout_seed.home_score,
            knockout_seed.away_score,
            knockout_seed.home_extra_score,
            knockout_seed.away_extra_score,
            knockout_seed.home_penalty_score,
            knockout_seed.away_penalty_score,
            NULL::SMALLINT AS match_day
        FROM knockout_seed
        JOIN world_cup_edition edition_row ON edition_row.year = knockout_seed.edition_year
        JOIN edition_phase edition_phase_row
            ON edition_phase_row.edition_id = edition_row.id
        JOIN competition_phase phase_row
            ON phase_row.id = edition_phase_row.phase_id
           AND phase_row.code = knockout_seed.phase_code
        JOIN edition_team_seed home_seed
            ON home_seed.edition_year = knockout_seed.edition_year
           AND home_seed.group_letter = LEFT(knockout_seed.home_slot_ref, 1)
           AND home_seed.group_slot = RIGHT(knockout_seed.home_slot_ref, 1)::SMALLINT
        JOIN edition_team_seed away_seed
            ON away_seed.edition_year = knockout_seed.edition_year
           AND away_seed.group_letter = LEFT(knockout_seed.away_slot_ref, 1)
           AND away_seed.group_slot = RIGHT(knockout_seed.away_slot_ref, 1)::SMALLINT
        JOIN edition_team_seed winner_seed
            ON winner_seed.edition_year = knockout_seed.edition_year
           AND winner_seed.group_letter = LEFT(knockout_seed.winner_slot_ref, 1)
           AND winner_seed.group_slot = RIGHT(knockout_seed.winner_slot_ref, 1)::SMALLINT
        JOIN edition_team home_team_row
            ON home_team_row.edition_id = edition_row.id
        JOIN team home_team_catalog ON home_team_catalog.id = home_team_row.team_id
           AND home_team_catalog.fifa_code = home_seed.team_code
        JOIN edition_team away_team_row
            ON away_team_row.edition_id = edition_row.id
        JOIN team away_team_catalog ON away_team_catalog.id = away_team_row.team_id
           AND away_team_catalog.fifa_code = away_seed.team_code
        JOIN edition_team winner_team_row
            ON winner_team_row.edition_id = edition_row.id
        JOIN team winner_team_catalog ON winner_team_catalog.id = winner_team_row.team_id
           AND winner_team_catalog.fifa_code = winner_seed.team_code
        JOIN stadium stadium_row ON stadium_row.name = knockout_seed.stadium_name
    ),
    inserted AS (
        INSERT INTO match_game (
            edition_id,
            edition_phase_id,
            group_id,
            stadium_id,
            kickoff_at,
            home_team_id,
            away_team_id,
            winner_team_id,
            home_score,
            away_score,
            home_extra_score,
            away_extra_score,
            home_penalty_score,
            away_penalty_score,
            match_day
        )
        SELECT *
        FROM (
            SELECT * FROM group_match_seed
            UNION ALL
            SELECT * FROM knockout_match_seed
        ) seeded_matches
        ORDER BY edition_id, kickoff_at, home_team_id, away_team_id
        RETURNING id
    )
    INSERT INTO synthetic_seed_registry (batch_id, table_name, primary_key)
    SELECT v_batch_id, 'match_game', jsonb_build_object('id', inserted.id)
    FROM inserted;

    WITH referee_seed AS (
        SELECT *
        FROM jsonb_to_recordset(v_referee_catalog) AS referee_seed(
            referee_seq INTEGER,
            full_name TEXT,
            country_name TEXT
        )
    ),
    referee_lookup AS (
        SELECT
            referee_seed.referee_seq,
            referee_row.id AS referee_id
        FROM referee_seed
        JOIN referee referee_row ON referee_row.full_name = referee_seed.full_name
    ),
    match_seed AS (
        SELECT
            match_row.id AS match_id,
            ROW_NUMBER() OVER (ORDER BY match_row.kickoff_at, match_row.id) AS match_seq
        FROM match_game match_row
        JOIN synthetic_seed_registry registry_row
            ON registry_row.batch_id = v_batch_id
           AND registry_row.table_name = 'match_game'
           AND registry_row.primary_key = jsonb_build_object('id', match_row.id)
    ),
    inserted AS (
        INSERT INTO match_official (match_id, referee_id, role)
        SELECT
            match_seed.match_id,
            referee_lookup.referee_id,
            assigned.role
        FROM match_seed
        CROSS JOIN LATERAL (
            VALUES
                (((match_seed.match_seq - 1) % 12) + 1, 'MAIN_REFEREE'::official_role),
                (((match_seed.match_seq + 2) % 12) + 1, 'ASSISTANT_REFEREE_1'::official_role),
                (((match_seed.match_seq + 5) % 12) + 1, 'ASSISTANT_REFEREE_2'::official_role),
                (((match_seed.match_seq + 8) % 12) + 1, 'FOURTH_OFFICIAL'::official_role)
        ) AS assigned(referee_seq, role)
        JOIN referee_lookup ON referee_lookup.referee_seq = assigned.referee_seq
        RETURNING match_id, referee_id
    )
    INSERT INTO synthetic_seed_registry (batch_id, table_name, primary_key)
    SELECT
        v_batch_id,
        'match_official',
        jsonb_build_object(
            'match_id', inserted.match_id,
            'referee_id', inserted.referee_id
        )
    FROM inserted;

    WITH seeded_matches AS (
        SELECT
            match_row.id AS match_id,
            match_row.edition_id,
            match_row.kickoff_at,
            match_row.match_day,
            match_row.home_team_id,
            match_row.away_team_id,
            match_row.winner_team_id,
            match_row.home_score,
            match_row.away_score,
            match_row.home_extra_score,
            match_row.away_extra_score,
            match_row.home_penalty_score,
            match_row.away_penalty_score,
            phase_row.code AS phase_code,
            team_group_row.group_letter
        FROM match_game match_row
        JOIN synthetic_seed_registry registry_row
            ON registry_row.batch_id = v_batch_id
           AND registry_row.table_name = 'match_game'
           AND registry_row.primary_key = jsonb_build_object('id', match_row.id)
        JOIN edition_phase edition_phase_row ON edition_phase_row.id = match_row.edition_phase_id
        JOIN competition_phase phase_row ON phase_row.id = edition_phase_row.phase_id
        LEFT JOIN team_group team_group_row ON team_group_row.id = match_row.group_id
    ),
    override_seed AS (
        SELECT
            seeded_matches.*,
            CASE
                WHEN seeded_matches.phase_code = 'GROUP_STAGE'
                 AND seeded_matches.group_letter IN ('A', 'C')
                 AND seeded_matches.match_day = 1
                 AND seeded_matches.kickoff_at::TIME = TIME '16:00'
                 AND seeded_matches.home_score >= 1
                    THEN 1
                ELSE 0
            END AS home_penalty_regular_count,
            CASE
                WHEN seeded_matches.phase_code = 'GROUP_STAGE'
                 AND seeded_matches.group_letter IN ('B', 'D')
                 AND seeded_matches.match_day = 2
                 AND seeded_matches.kickoff_at::TIME = TIME '20:00'
                 AND seeded_matches.away_score >= 1
                    THEN 1
                ELSE 0
            END AS away_penalty_regular_count,
            CASE
                WHEN seeded_matches.phase_code = 'GROUP_STAGE'
                 AND seeded_matches.group_letter = 'A'
                 AND seeded_matches.match_day = 2
                 AND seeded_matches.kickoff_at::TIME = TIME '16:00'
                 AND seeded_matches.home_score >= 1
                    THEN 1
                ELSE 0
            END AS home_goals_from_away_own_goal,
            CASE
                WHEN seeded_matches.phase_code = 'GROUP_STAGE'
                 AND seeded_matches.group_letter = 'D'
                 AND seeded_matches.match_day = 1
                 AND seeded_matches.kickoff_at::TIME = TIME '20:00'
                 AND seeded_matches.away_score >= 1
                    THEN 1
                ELSE 0
            END AS away_goals_from_home_own_goal
        FROM seeded_matches
    ),
    goal_plan AS (
        SELECT
            override_seed.match_id,
            override_seed.edition_id,
            override_seed.home_team_id AS team_id,
            'GOAL'::game_event_type AS event_type,
            CASE goal_index
                WHEN 1 THEN 9
                WHEN 2 THEN 10
                WHEN 3 THEN 11
                ELSE 8
            END::SMALLINT AS shirt_number,
            (12 + (goal_index - 1) * 17)::SMALLINT AS event_minute,
            0::SMALLINT AS stoppage_minute,
            'Open-play finish for the home side.'::TEXT AS description
        FROM override_seed
        CROSS JOIN LATERAL generate_series(
            1,
            GREATEST(
                override_seed.home_score
                - override_seed.home_penalty_regular_count
                - override_seed.home_goals_from_away_own_goal,
                0
            )
        ) AS goal_index(goal_index)

        UNION ALL

        SELECT
            override_seed.match_id,
            override_seed.edition_id,
            override_seed.home_team_id,
            'PENALTY_GOAL'::game_event_type,
            10::SMALLINT,
            44::SMALLINT,
            0::SMALLINT,
            'Penalty converted by the home side.'::TEXT
        FROM override_seed
        WHERE override_seed.home_penalty_regular_count = 1

        UNION ALL

        SELECT
            override_seed.match_id,
            override_seed.edition_id,
            override_seed.away_team_id,
            'OWN_GOAL'::game_event_type,
            4::SMALLINT,
            35::SMALLINT,
            0::SMALLINT,
            'Own goal that lifted the home team.'::TEXT
        FROM override_seed
        WHERE override_seed.home_goals_from_away_own_goal = 1

        UNION ALL

        SELECT
            override_seed.match_id,
            override_seed.edition_id,
            override_seed.away_team_id AS team_id,
            'GOAL'::game_event_type AS event_type,
            CASE goal_index
                WHEN 1 THEN 9
                WHEN 2 THEN 11
                WHEN 3 THEN 10
                ELSE 8
            END::SMALLINT AS shirt_number,
            (18 + (goal_index - 1) * 19)::SMALLINT AS event_minute,
            0::SMALLINT AS stoppage_minute,
            'Open-play finish for the away side.'::TEXT AS description
        FROM override_seed
        CROSS JOIN LATERAL generate_series(
            1,
            GREATEST(
                override_seed.away_score
                - override_seed.away_penalty_regular_count
                - override_seed.away_goals_from_home_own_goal,
                0
            )
        ) AS goal_index(goal_index)

        UNION ALL

        SELECT
            override_seed.match_id,
            override_seed.edition_id,
            override_seed.away_team_id,
            'PENALTY_GOAL'::game_event_type,
            10::SMALLINT,
            52::SMALLINT,
            0::SMALLINT,
            'Penalty converted by the away side.'::TEXT
        FROM override_seed
        WHERE override_seed.away_penalty_regular_count = 1

        UNION ALL

        SELECT
            override_seed.match_id,
            override_seed.edition_id,
            override_seed.home_team_id,
            'OWN_GOAL'::game_event_type,
            5::SMALLINT,
            41::SMALLINT,
            0::SMALLINT,
            'Own goal that brought the away team back into the match.'::TEXT
        FROM override_seed
        WHERE override_seed.away_goals_from_home_own_goal = 1

        UNION ALL

        SELECT
            override_seed.match_id,
            override_seed.edition_id,
            override_seed.home_team_id,
            'GOAL'::game_event_type,
            CASE goal_index
                WHEN 1 THEN 9
                ELSE 10
            END::SMALLINT,
            (96 + (goal_index - 1) * 12)::SMALLINT,
            0::SMALLINT,
            'Extra-time goal for the home side.'::TEXT
        FROM override_seed
        CROSS JOIN LATERAL generate_series(1, GREATEST(override_seed.home_extra_score, 0)) AS goal_index(goal_index)

        UNION ALL

        SELECT
            override_seed.match_id,
            override_seed.edition_id,
            override_seed.away_team_id,
            'GOAL'::game_event_type,
            CASE goal_index
                WHEN 1 THEN 9
                ELSE 10
            END::SMALLINT,
            (103 + (goal_index - 1) * 10)::SMALLINT,
            0::SMALLINT,
            'Extra-time goal for the away side.'::TEXT
        FROM override_seed
        CROSS JOIN LATERAL generate_series(1, GREATEST(override_seed.away_extra_score, 0)) AS goal_index(goal_index)
    ),
    card_plan AS (
        SELECT
            seeded_matches.match_id,
            seeded_matches.edition_id,
            CASE
                WHEN mod(seeded_matches.match_id, 2) = 0 THEN seeded_matches.away_team_id
                ELSE seeded_matches.home_team_id
            END AS team_id,
            'YELLOW_CARD'::game_event_type AS event_type,
            6::SMALLINT AS shirt_number,
            63::SMALLINT AS event_minute,
            0::SMALLINT AS stoppage_minute,
            'Late tactical yellow card.'::TEXT AS description
        FROM seeded_matches

        UNION ALL

        SELECT
            seeded_matches.match_id,
            seeded_matches.edition_id,
            CASE
                WHEN seeded_matches.home_team_id = seeded_matches.winner_team_id THEN seeded_matches.home_team_id
                WHEN seeded_matches.away_team_id = seeded_matches.winner_team_id THEN seeded_matches.away_team_id
                ELSE seeded_matches.home_team_id
            END AS team_id,
            'SUBSTITUTION'::game_event_type AS event_type,
            9::SMALLINT AS shirt_number,
            72::SMALLINT AS event_minute,
            0::SMALLINT AS stoppage_minute,
            'Attacking substitution to manage the final phase of the match.'::TEXT AS description
        FROM seeded_matches

        UNION ALL

        SELECT
            seeded_matches.match_id,
            seeded_matches.edition_id,
            CASE
                WHEN seeded_matches.winner_team_id = seeded_matches.home_team_id THEN seeded_matches.away_team_id
                WHEN seeded_matches.winner_team_id = seeded_matches.away_team_id THEN seeded_matches.home_team_id
                ELSE seeded_matches.away_team_id
            END AS team_id,
            'RED_CARD'::game_event_type,
            4::SMALLINT,
            85::SMALLINT,
            0::SMALLINT,
            'Straight red card after denying a clear chance.'::TEXT
        FROM seeded_matches
        WHERE seeded_matches.phase_code IN ('SEMIFINAL', 'FINAL')
    ),
    inserted AS (
        INSERT INTO match_event (
            match_id,
            event_minute,
            stoppage_minute,
            event_type,
            team_id,
            player_id,
            related_player_id,
            description
        )
        SELECT
            goal_plan.match_id,
            goal_plan.event_minute,
            goal_plan.stoppage_minute,
            goal_plan.event_type,
            goal_plan.team_id,
            call_up_row.player_id,
            NULL::BIGINT,
            goal_plan.description
        FROM goal_plan
        JOIN team_call_up call_up_row
            ON call_up_row.edition_id = goal_plan.edition_id
           AND call_up_row.team_id = goal_plan.team_id
           AND call_up_row.shirt_number = goal_plan.shirt_number

        UNION ALL

        SELECT
            card_plan.match_id,
            card_plan.event_minute,
            card_plan.stoppage_minute,
            card_plan.event_type,
            card_plan.team_id,
            outgoing_row.player_id,
            CASE
                WHEN card_plan.event_type = 'SUBSTITUTION' THEN incoming_row.player_id
                ELSE NULL::BIGINT
            END AS related_player_id,
            card_plan.description
        FROM card_plan
        JOIN team_call_up outgoing_row
            ON outgoing_row.edition_id = card_plan.edition_id
           AND outgoing_row.team_id = card_plan.team_id
           AND outgoing_row.shirt_number = card_plan.shirt_number
        LEFT JOIN team_call_up incoming_row
            ON incoming_row.edition_id = card_plan.edition_id
           AND incoming_row.team_id = card_plan.team_id
           AND incoming_row.shirt_number = 14
        RETURNING id
    )
    INSERT INTO synthetic_seed_registry (batch_id, table_name, primary_key)
    SELECT v_batch_id, 'match_event', jsonb_build_object('id', inserted.id)
    FROM inserted;

    UPDATE world_cup_edition edition_row
    SET champion_team_id = champion_team.id,
        vice_champion_team_id = vice_team.id,
        third_place_team_id = third_team.id
    FROM team champion_team,
         team vice_team,
         team third_team
    WHERE edition_row.year = 2034
      AND champion_team.fifa_code = 'AUR'
      AND vice_team.fifa_code = 'IVE'
      AND third_team.fifa_code = 'MRD';

    UPDATE world_cup_edition edition_row
    SET champion_team_id = champion_team.id,
        vice_champion_team_id = vice_team.id,
        third_place_team_id = third_team.id
    FROM team champion_team,
         team vice_team,
         team third_team
    WHERE edition_row.year = 2038
      AND champion_team.fifa_code = 'IVE'
      AND vice_team.fifa_code = 'AUR'
      AND third_team.fifa_code = 'FJD';

    RETURN QUERY
    SELECT
        'populate'::TEXT AS operation,
        'seeded'::TEXT AS status,
        summary_row.batch_id AS active_batch_id,
        summary_row.edition_years,
        summary_row.table_counts,
        summary_row.total_rows,
        'Synthetic dataset seeded successfully.'::TEXT AS message
    FROM fn_internal_synthetic_batch_summary(v_batch_id) summary_row;
END;
$synthetic$;

CREATE OR REPLACE FUNCTION fn_cleanup_synthetic_data()
RETURNS TABLE (
    operation TEXT,
    status TEXT,
    active_batch_id BIGINT,
    edition_years SMALLINT[],
    table_counts JSONB,
    total_rows BIGINT,
    message TEXT
)
LANGUAGE plpgsql
SET search_path = world_cup, public
AS $cleanup$
DECLARE
    v_batch_id BIGINT;
    v_table_name TEXT;
    v_registry_row RECORD;
    v_expected_count BIGINT;
    v_deleted_count BIGINT;
    v_deleted_step BIGINT;
BEGIN
    PERFORM fn_internal_acquire_synthetic_seed_lock();

    SELECT batch_row.id
    INTO v_batch_id
    FROM synthetic_seed_batch batch_row
    WHERE batch_row.is_active = TRUE
    ORDER BY batch_row.id DESC
    LIMIT 1;

    IF v_batch_id IS NULL THEN
        RETURN QUERY
        SELECT
            'cleanup'::TEXT AS operation,
            'nothing_to_clean'::TEXT AS status,
            NULL::BIGINT AS active_batch_id,
            ARRAY[]::SMALLINT[] AS edition_years,
            '{}'::JSONB AS table_counts,
            0::BIGINT AS total_rows,
            'No active synthetic dataset was found.'::TEXT AS message;
        RETURN;
    END IF;

    FOR v_table_name IN
        SELECT unnest(ARRAY[
            'match_event',
            'match_official',
            'match_game',
            'team_call_up',
            'edition_team',
            'team_group',
            'edition_phase',
            'edition_host_city',
            'world_cup_edition',
            'stadium',
            'host_city',
            'player',
            'referee',
            'coach',
            'competition_phase',
            'team',
            'country',
            'confederation'
        ]::TEXT[])
    LOOP
        SELECT COUNT(*)::BIGINT
        INTO v_expected_count
        FROM synthetic_seed_registry registry_row
        WHERE registry_row.batch_id = v_batch_id
          AND registry_row.table_name = v_table_name;

        v_deleted_count := 0;

        FOR v_registry_row IN
            SELECT registry_row.primary_key
            FROM synthetic_seed_registry registry_row
            WHERE registry_row.batch_id = v_batch_id
              AND registry_row.table_name = v_table_name
            ORDER BY registry_row.id DESC
        LOOP
            CASE v_table_name
                WHEN 'match_event' THEN
                    DELETE FROM match_event
                    WHERE id = (v_registry_row.primary_key ->> 'id')::BIGINT;
                WHEN 'match_official' THEN
                    DELETE FROM match_official
                    WHERE match_id = (v_registry_row.primary_key ->> 'match_id')::BIGINT
                      AND referee_id = (v_registry_row.primary_key ->> 'referee_id')::BIGINT;
                WHEN 'match_game' THEN
                    DELETE FROM match_game
                    WHERE id = (v_registry_row.primary_key ->> 'id')::BIGINT;
                WHEN 'team_call_up' THEN
                    DELETE FROM team_call_up
                    WHERE edition_id = (v_registry_row.primary_key ->> 'edition_id')::BIGINT
                      AND team_id = (v_registry_row.primary_key ->> 'team_id')::BIGINT
                      AND player_id = (v_registry_row.primary_key ->> 'player_id')::BIGINT;
                WHEN 'edition_team' THEN
                    DELETE FROM edition_team
                    WHERE id = (v_registry_row.primary_key ->> 'id')::BIGINT;
                WHEN 'team_group' THEN
                    DELETE FROM team_group
                    WHERE id = (v_registry_row.primary_key ->> 'id')::BIGINT
                      AND edition_id = (v_registry_row.primary_key ->> 'edition_id')::BIGINT;
                WHEN 'edition_phase' THEN
                    DELETE FROM edition_phase
                    WHERE id = (v_registry_row.primary_key ->> 'id')::BIGINT
                      AND edition_id = (v_registry_row.primary_key ->> 'edition_id')::BIGINT;
                WHEN 'edition_host_city' THEN
                    DELETE FROM edition_host_city
                    WHERE edition_id = (v_registry_row.primary_key ->> 'edition_id')::BIGINT
                      AND host_city_id = (v_registry_row.primary_key ->> 'host_city_id')::BIGINT;
                WHEN 'world_cup_edition' THEN
                    DELETE FROM world_cup_edition
                    WHERE id = (v_registry_row.primary_key ->> 'id')::BIGINT;
                WHEN 'stadium' THEN
                    DELETE FROM stadium
                    WHERE id = (v_registry_row.primary_key ->> 'id')::BIGINT;
                WHEN 'host_city' THEN
                    DELETE FROM host_city
                    WHERE id = (v_registry_row.primary_key ->> 'id')::BIGINT;
                WHEN 'player' THEN
                    DELETE FROM player
                    WHERE id = (v_registry_row.primary_key ->> 'id')::BIGINT;
                WHEN 'referee' THEN
                    DELETE FROM referee
                    WHERE id = (v_registry_row.primary_key ->> 'id')::BIGINT;
                WHEN 'coach' THEN
                    DELETE FROM coach
                    WHERE id = (v_registry_row.primary_key ->> 'id')::BIGINT;
                WHEN 'competition_phase' THEN
                    DELETE FROM competition_phase
                    WHERE id = (v_registry_row.primary_key ->> 'id')::BIGINT;
                WHEN 'team' THEN
                    DELETE FROM team
                    WHERE id = (v_registry_row.primary_key ->> 'id')::BIGINT;
                WHEN 'country' THEN
                    DELETE FROM country
                    WHERE id = (v_registry_row.primary_key ->> 'id')::BIGINT;
                WHEN 'confederation' THEN
                    DELETE FROM confederation
                    WHERE id = (v_registry_row.primary_key ->> 'id')::BIGINT;
                ELSE
                    RAISE EXCEPTION 'Unsupported synthetic cleanup table: %', v_table_name;
            END CASE;

            GET DIAGNOSTICS v_deleted_step = ROW_COUNT;
            v_deleted_count := v_deleted_count + v_deleted_step;
        END LOOP;

        IF v_deleted_count <> v_expected_count THEN
            RAISE EXCEPTION
                'Synthetic cleanup drift detected for table %: expected %, deleted %.',
                v_table_name,
                v_expected_count,
                v_deleted_count;
        END IF;
    END LOOP;

    UPDATE synthetic_seed_batch
    SET is_active = FALSE,
        cleaned_at = NOW()
    WHERE id = v_batch_id;

    RETURN QUERY
    SELECT
        'cleanup'::TEXT AS operation,
        'cleaned'::TEXT AS status,
        summary_row.batch_id AS active_batch_id,
        summary_row.edition_years,
        summary_row.table_counts,
        summary_row.total_rows,
        'Synthetic dataset cleaned successfully.'::TEXT AS message
    FROM fn_internal_synthetic_batch_summary(v_batch_id) summary_row;
END;
$cleanup$;

COMMIT;
